site:
  title: NicksHomeLab, hackity hack
  url: https://nickhardiman.netlify.app
  start_page: articles:ROOT:index.adoc
  keys:
    google_analytics: 'G-7K2RCE6KXL'
content:
  sources: 
  - url: https://github.com/nickhardiman/articles.git
    branches: main
ui: 
  bundle:
    url: https://github.com/nickhardiman/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    experimental: true 
    page-pagination: true 
