site:
  title: Nick Hardiman, Red Hat consultant
  url: https://nickhardiman.netlify.app
  start_page: articles:ROOT:index.adoc
content:
  sources: 
  - url: https://github.com/nickhardiman/articles.git
    branches: main
ui: 
  bundle:
    url: https://github.com/nickhardiman/antora-ui/blob/master/build/ui-bundle.zip
    snapshot: true

