= update packages with DNF
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 12-01-2021

Connect with SSH and update packages with DNF.

== errata (updates, bug fixes and security patches)

Red Hat calls package updates _errata_ or _advisories_. There are three types. 

* A Red Hat Security Advisory (RHSA) package fixes security problems. 
* A Red Hat Bug Advisory (RHBA) fixes code problems. 
* A Red Hat Enhancement Advisory (RHEA) provides new features. 

For more information, read the article https://access.redhat.com/articles/2130961[Explaining Red Hat Errata (RHSA, RHBA, and RHEA)].

== install 

DNF packages are already installed. 
There's the dnf package which provides dnf itself, dnf-plugins-core which extends what dnf can do, python3-dnf which fills up /usr/lib/python3.6/site-packages/dnf/, and others.   

These packages provide DNF version 4. 

[source,shell]
----
[root@host1 images]# dnf --version
4.2.23
  Installed: dnf-0:4.2.23-4.el8.noarch at Tue 05 Jan 2021 13:49:10 GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Wed 29 Jul 2020 12:23:18 GMT

  Installed: rpm-0:4.14.3-4.el8.x86_64 at Tue 05 Jan 2021 13:46:56 GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Fri 26 Jun 2020 15:03:24 GMT
[root@host1 images]# 
----



== view errata

Use DNF to list all the updates this machine can get. 

[source,shell]
----
[root@host1 ~]# dnf updateinfo --list
Updating Subscription Management repositories.
Last metadata expiration check: 1:22:40 ago on Tue 12 Jan 2021 08:26:33 GMT.
RHSA-2021:0052 Critical/Sec. firefox-78.6.1-1.el8_3.x86_64
RHEA-2020:4727 enhancement   perl-Carp-1.50-439.module+el8.3.0+6718+7f269185.noarch
RHBA-2019:3337 bugfix        perl-DBD-SQLite-1.58-2.module+el8.1.0+2940+55ca6856.x86_64
...
----

You can find out more about https://access.redhat.com/errata/#/[Red Hat Product Errata] on the https://access.redhat.com/[customer portal].
Security administrators can also search the  https://access.redhat.com/security/security-updates/#/cve[Red Hat CVE (Common Security Advisory) database].


== download repositories 

Packages will be downloaded from enabled repositories. 

[source,shell]
----
[root@host1 ~]# dnf repolist 
Updating Subscription Management repositories.
repo id                                               repo name
ansible-2-for-rhel-8-x86_64-rpms                      Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)
rhel-8-for-x86_64-appstream-rpms                      Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                         Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
[root@host1 ~]# 
----


== update 

[source,shell]
----
[root@host1 ~]# dnf -y update
Updating Subscription Management repositories.
Last metadata expiration check: 0:04:07 ago on Tue 05 Jan 2021 14:10:14 GMT.
Dependencies resolved.
...
Transaction Summary
======================================================
Install   3 Packages
Upgrade  74 Packages
...
Installed:
  kernel-4.18.0-240.10.1.el8_3.x86_64    kernel-core-4.18.0-240.10.1.el8_3.x86_64    kernel-modules-4.18.0-240.10.1.el8_3.x86_64   

Complete!
[root@host1 ~]# 
----

Install media don't get updated with the latest packages. 
The older the ISO file, the more packages require updates. 
Here, the kernel is updated. 


== reboot if the kernel is updated

Reboot to swap from the current kernel to the new one. 


[source,shell]
----
[root@host1 ~]# systemctl reboot
[root@host1 ~]# Connection to host1 closed by remote host.
Connection to host1 closed.
MacBook-Pro:~ nick$ 
----


