=  first stage boot loader (BIOS or UEFI)
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 18-08-2020

What happens when booting a VM, from start to login prompt.

Much of the boot process doesn't apply to virtual machines. 
Virtual machines don't have any hardware, let alone power hardware, 
but a VM management system will emulate some parts. 
For instance, a graphical system will display a power button to turn on a VM, and an https://en.wikipedia.org/wiki/Advanced_Configuration_and_Power_Interface[ACPI] command can turn off a VM. 




== boot first stage

Many types of firmware exist to manage the boot process. 
There are many different products for general purpose computers like PCs, and many more for special purpose computers like network equipment and storage devices. 
Most of it is proprietary, treated as IP (Intellectual Property) and kept secret by hardware vendors. 

Usually there's a chain of programs to run. The first program is often tiny, and does little more than figure out how to load the next much bigger program.

* The CPU loads the first part of the boot loader program, executes the first command, and does what it's told.  
* The first boot loader does its work, loads the next program from storage, and finishes. 
* The next program does its work, and hands over to another program in the chain.

New PC firmware works with the UEFI specification, and older PC firmware works with the BIOS specification. 


=== BIOS 


Guest virtual machines get an open source product called https://seabios.org/SeaBIOS[SeaBIOS] by default. 
The QEMU hypervisor includes this BIOS. 

For instance, when the BIOS hands over to GRUB, it first loads a tiny 
https://www.gnu.org/software/grub/manual/grub/html_node/Images.html[boot.img] file from the 
https://en.wikipedia.org/wiki/Master_boot_record[MBR (Master Boot Record)] - that's the 512 byte sector at the very start of the disk. This boot image is a program that does nothing except kick off the next GRUB program. There isn't enough room in the MBR to store anything interesting. 


=== UEFI 

The physical host machine probably uses UEFI, unless its several years old. 

not using EFI

[source,shell]
----
[nick@guest1 ~]$ ls /sys/firmware/efi
ls: cannot access '/sys/firmware/efi': No such file or directory
[nick@guest1 ~]$ 
[nick@guest1 ~]$ efibootmgr 
EFI variables are not supported on this system.
[nick@guest1 ~]$ 
----


