= create _guest4_ using a KVM image
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 14-01-2021



Use libvirt to create the _guest4_ virtual machine. 

Use a  *golden image* process. 
Use a disk file that already has the OS installed - this is the golden image. 
Make a copy of this image.

The ready-made _guest4_ disk image is a copy of the golden image (the RHEL 8 KVM file).
This is a minimal install containing a couple hundred packages. 
This new copy is used to build the new _guest4_ virtual machine. 





== create the libvirt domain 

Create a VM using the ready-made _guest4_ disk image. 


=== using XML config 

A new VM can be created using a command like ``virsh define my-machine.xml``, 
similar to the way a storage pool can be created using ``virsh pool-define storage-pool.xml``.

ut the XML configuration that defines a virtual machine is complicated. 
It's easier to use the ``virt-install`` command to do the hard work. 


=== using the virt-install command

This ``virt-install`` command is pretty long, so it's split over many lines to make it a little clearer. 
And the values are parameterized to make them clearer, too.  

These are the values.

[source,bash]
----
HOST=guest4 
CPUS=1
MEMORY=2048
POOL=images
VOLUME=$HOST.qcow2
OS_VARIANT=rhel8.3
IF1_MAC=52:54:00:00:00:03
IF1_BRIDGE=privbr0
----

This version of the virt-install command is different to the ones used to create _myfirstvm_ and _guest1_. 

[source,bash]
----
virt-install   \
    --name       $HOST   \
    --vcpus      $CPUS \
    --memory     $MEMORY \
    --disk       vol=$POOL/$VOLUME  \
    --os-variant $OS_VARIANT \
    --network    bridge:${IF1_BRIDGE},mac=$IF1_MAC   \
    --import   \
    --noautoconsole
----

Here's an explanation of what's going on. 

* --name sets the name that libvirt uses (not the OS hostname). 
* --vcpus, --ram, --disk - The next three options add resources - 1 CPU, 2048MiB memory and a 10GiB disk.
* --boot sets the firmware -   UEFI rather than the older BIOS.
* --os-variant sets up some default values. 
The command ``osinfo-query os`` lists all the choices. 
* --network defines the ethernet interface and which libvirt network it's connected to.
* --import - use the disk to boot the new VM. 
* --noautoconsole - when the virt-install command kicks off the build of the VM, don't hang around and connect to the console. 
That's done as a seperate step. 

Read `man virt-install` for all the options (and there are a truck-load). 
The virt-install tool has a lot of default settings, so there is no need to specify options like `--connect qemu:///system` for the hypervisor and `--graphics spice` for a graphical desktop. 



Create a new VM using a ready-made disk image.
Copy and paste the values, then the virt-install command. 

The command is pretty quick. 

[source,shell]
----
[root@host1 ~]# HOST=guest4 
[root@host1 ~]# CPUS=1
[root@host1 ~]# MEMORY=2048
[root@host1 ~]# POOL=images
[root@host1 ~]# VOLUME=$HOST.qcow2
[root@host1 ~]# OS_VARIANT=rhel8.3
[root@host1 ~]# IF1_MAC=52:54:00:00:00:03
[root@host1 ~]# IF1_BRIDGE=privbr0
[root@host1 ~]# virt-install   \
>     --name       $HOST   \
>     --vcpus      $CPUS \
>     --memory     $MEMORY \
>     --disk       vol=$POOL/$VOLUME  \
>     --os-variant $OS_VARIANT \
>     --network    bridge:${IF1_BRIDGE},mac=$IF1_MAC   \
>     --import   \
>     --noautoconsole
Starting install...
Domain creation completed.
[root@host1 ~]# 
----

libvirt adds XML configuration 

Now there is a VM.

[source,shell]
----
[root@host1 ~]# virsh list --all
 Id   Name     State
------------------------
 1    guest1   running
 6    guest4   running

[root@host1 ~]# 
----



== use the console 

Connect to the console with the ``virsh console`` command.
Hit the Enter key kbd:[⏎]  to get the _guest4 login_ prompt to appear. 

[source,shell]
----
[root@host1 ~]# virsh console guest4
Connected to domain guest4
Escape character is ^]

Red Hat Enterprise Linux 8.3 (Ootpa)
Kernel 4.18.0-240.1.1.el8_3.x86_64 on an x86_64

Activate the web console with: systemctl enable --now cockpit.socket

guest4 login: 
----

That's enough to prove the virtual machine runs. 

Disconnect from the console. 
The disconnection command is 
kbd:[Ctrl + ++]++ ] 


[source,shell]
----
^]
[root@host1 ~]# 
----



== delete the VM

if something goes wrong, clear your work and start again with the  _virsh undefine_ command.

First, stop the VM running with the _virsh destroy_ command. 
Despite the dramatic _destroy_ name, this does not delete anything. 
It's like pulling the plug on a physical computer. 

[source,shell]
----
[root@host1 ~]# virsh destroy guest4
Domain guest4 destroyed

[root@host1 ~]# 
[root@host1 ~]# virsh undefine --nvram --remove-all-storage guest4 
Domain guest4 has been undefined
Volume 'vda'(/var/lib/libvirt/images/guest4.qcow2) removed.

[root@host1 ~]# 
----

Check it's gone. 

[source,shell]
....
[root@host1 ~]# virsh list --all
 Id   Name     State
------------------------
 1    guest1   running

[root@host1 ~]# 
....



