= Red Hat Ansible Engine
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 01-06-2020

Install Red Hat Ansible Engine using your Red Hat Developer Subscription.

== Red Hat's management technology

Red Hat supports many tools for automation and management.

* https://www.redhat.com/en/technologies/management/ansible[Red Hat Ansible Automation Platform]
* https://www.redhat.com/en/technologies/management/satellite[Red Hat Satellite]
* https://www.redhat.com/en/technologies/management/insights[Red Hat Insights]

https://www.ansible.com/products/engine[Ansible Engine] is one of Red Hat's products in the Automation Platform. Ansible Engine is an automation system, good for provisioning new systems and deploying applications. 
Thousands of modules are included to manage Linux, Windows, on-premise network kit, off-premise cloud services, physical machines and virtual.


== Red Hat Ansible Engine

Like all Red Hat products, Red Hat Ansible Engine is the result of taking an upstream open source project and delivering an enterprise product. 
The ridiculously busy https://github.com/ansible/ansible[upstream project] is, of course, Ansible.
It's popular with pretty much everyone everywhere. 

Red Hat make sure the Ansible Engine product is  enterprise-ready by improving stability, security and scalability, and https://access.redhat.com/support/policy/updates/ansible-engine[supporting the lifecycle]. Subscribed systems download errata updates from the Red Hat CDN, for the 
https://access.redhat.com/support/policy/updates/ansible-engine[lifetime of Ansible Engine]. 


== Ansible Engine and the developer subscription 

The developer subscription provides Ansible Engine. If you run the command ``subscription-manager list --consumed`` on a registered system, you see _Red Hat Ansible Engine_ in the list of 50 products.

https://access.redhat.com/products/red-hat-ansible-engine[Ansible Engine] is part of the 
https://www.redhat.com/en/technologies/management/ansible[Red Hat Ansible Automation Platform].
Your developer subscription does not entitle you to download other Automation Platform components, like Ansible Tower. For that, you need a Red Hat Ansible Automation Platform subscription.
If you want to try the whole Automation Platform, you can https://www.redhat.com/en/technologies/management/ansible/try-it[sign up for a 60 day trial subscription] for free.

The limited supported version of Ansible Engine is available in Red Hat's CDN (Content Delivery Network). 



== prerequisites 

This article assumes you have already carried out these steps.  

. sign up for a developer account.
. prepare your workstation
. install RHEL 8
. complete system registration and subscription  
. create a virtual machine

There are  many commands shown here, along with their output. 
After you carry out these steps, you will see the same results when you run the commands.

Start the VM.

Log in.

[source,shell]
....
[nick@host ~]$ ssh 192.168.122.218
nick@192.168.122.218's password: 
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed May 27 13:26:47 2020
[nick@guest1 ~]$ 
....


== view ansible repositories

Ansible repositories are configured, but not enabled. There is one major version available (2) and a couple minor versions (8 and 9).

Most users ignore repositories ending in ``-source-rpms`` and ``-debug-rpms``.
Source packages are useful to those who know how to code and compile. 
Debug packages contain compiled programs with extra information, useful for those who know their way around a debugger.

[source,shell]
----
[nick@guest1 ~]$ sudo subscription-manager repos --list | grep ansible
[sudo] password for nick: 
Repo ID:   ansible-2.8-for-rhel-8-x86_64-source-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.8/source/SRPMS
...
Repo ID:   ansible-2.9-for-rhel-8-x86_64-debug-rpms
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.9/debug
[nick@guest1 ~]$ 
----


The repository ``ansible-2-for-rhel-8-x86_64-rpms`` points to the latest version. 

If you want to know more about the repo, have a look at the configuration file /etc/yum.repos.d/redhat.repo. Each repo has a section in here with a dozen attributes that influence how _dnf_ works.

* The dnf command can't install ansible yet because the ``enabled`` attribute is false (0).  
* Attribute names starting with ``ssl`` are used to authenticate to the CDN.
* Attributes starting with ``gpg`` are used to check package integrity. 


[source,shell]
----
[nick@guest1 ~]$ grep -A12 ansible-2-for-rhel-8-x86_64-rpms /etc/yum.repos.d/redhat.repo 
[ansible-2-for-rhel-8-x86_64-rpms]
name = Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)
baseurl = https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/os
enabled = 0
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
sslverify = 1
sslcacert = /etc/rhsm/ca/redhat-uep.pem
sslclientkey = /etc/pki/entitlement/1234567890123456789-key.pem
sslclientcert = /etc/pki/entitlement/1234567890123456789.pem
metadata_expire = 86400
enabled_metadata = 1

[nick@guest1 ~]$ 
----


== enable one repository 

Enable the repository ``ansible-2-for-rhel-8-x86_64-rpms``. 

[source,shell]
----
[nick@guest1 ~]$ sudo subscription-manager repos --enable=ansible-2-for-rhel-8-x86_64-rpms
[sudo] password for nick: 
Repository 'ansible-2-for-rhel-8-x86_64-rpms' is enabled for this system.
[nick@guest1 ~]$ 
----

Check your work by viewing available ansible packages. 
The name of the Ansible Engine package is 'ansible'.

[source,shell]
----
[nick@guest1 ~]$ sudo dnf search ansible
Updating Subscription Management repositories.
Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)                                                   1.5 MB/s | 1.1 MB     00:00    
Last metadata expiration check: 0:00:01 ago on Tue 26 May 2020 12:56:47 BST.
================================================== Name Exactly Matched: ansible ===================================================
ansible.noarch : SSH-based configuration management, deployment, and task execution system
================================================= Name & Summary Matched: ansible ==================================================
ansible-test.noarch : Tool for testing ansible plugin and module code
====================================================== Name Matched: ansible =======================================================
ansible-freeipa.noarch : Roles and playbooks to deploy FreeIPA servers, replicas and clients
[nick@guest1 ~]$ 
----


== install ansible 

Install ansible with the command ``sudo dnf install ansible``.

RHEL 8 comes with its own copy of Python (the executable is /usr/libexec/platform-python).
Ansible uses the OS's python, not any python installed by the user. 

Check your work by displaying the default configuration.

[source,shell]
----
[nick@guest1 ~]$ ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nick/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
[nick@guest1 ~]$ 
----


== use ansible 

Try a few safe commands.

Use the ping module. 

[source,shell]
----
[nick@guest1 ~]$ ansible -m ping localhost
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
[nick@guest1 ~]$ 
----

List the thousands of included modules.

[source,shell]
----
[nick@guest1 ~]$ ansible-doc -l
a10_server                                                    Manage A10 Ne...
a10_server_axapi3                                             Manage A10 Ne...
a10_service_group                                             Manage A10 Ne...
...
zpool_facts                                                   Gather facts ...
zypper                                                        Manage packag...
zypper_repository                                             Add and remov...
[nick@guest1 ~]$ 
----


== next steps 

?
automate the install

python3 virtualenv

install molecule


