= install the container tools dnf module
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 01-06-2020


Install the container-tools module and run a container.

.a container in a virtual machine in a physical machine
....
.-------------------------------------.
|                                     |    
|   host physical machine             |    
|                                     |    
|   .-----------------------------.   |    
|   |                             |   |   
|   |  guest virtual machine      |   |
|   |                             |   |  
|   |   +---------------------+   |   |  
|   |   |                     |   |   |  
|   |   | container           |   |   |  
|   |   |                     |   |   |  
|   |   +---------------------+   |   |  
|   |                             |   |  
|   .-----------------------------.   |  
.-------------------------------------.  
....

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index[Get started with containers].

The https://fedoraproject.org/wiki/DNF[DNF] module *container-tools* provides tools for working with Linux containers. 

== actual container tools 

The container-tools module is a bundle of tools, libraries and extensions, including these.

* https://github.com/cockpit-project/cockpit-podman[cockpit-podman], a cockpit extension for managing your containers with a web UI.
* https://github.com/containers/libpod[podman], the container management tool for sysadmins and developers.
* https://github.com/opencontainers/runc[runc], the container runtime tool that turns container images into running containers.

If you haven't got to grips yet with the confusing terminology of the container world, you're not alone. 
This 
https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction/[Practical Introduction to Container Terminology] can help.


== container-tools the module 

The https://access.redhat.com/support/policy/updates/containertools[Container Tools AppStream] provides three streams for container-tools.

* rhel8 is a rolling stream that will be supported and updated for the entire lifetime of RHEL 8. This is the default. 
* 1.0 is a stable stream that was released with RHEL 8.0. 
* 2.0 is the current stable stream, released with RHEL 8.2. 

[source,shell]
----
[nick@guest1 ~]$ sudo dnf module list container-tools
Updating Subscription Management repositories.
Last metadata expiration check: 2:10:50 ago on Thu 04 Jun 2020 16:44:27 EDT.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Name            Stream    Profiles   Summary                                             
container-tools rhel8 [d] common [d] Common tools and dependencies for container runtimes
container-tools 1.0       common [d] Common tools and dependencies for container runtimes
container-tools 2.0       common [d] Common tools and dependencies for container runtimes

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
[nick@guest1 ~]$ 
----


== install 

Install with the command ``sudo dnf module install container-tools``.

Want to delete the module? Change `install` to `remove`.


=== remove 


== check your work 


