= container buildah
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 31-07-2020


Build a new container from scratch.

Create a container image containing a simple web service. 
This service is written in Perl, using a web framework called https://mojolicious.org/[mojolicious]. 
The dnf package utility installs RPM packages that provide the OS and application, and 
perl installs the perl modules for the web service.

This procedure doesn't use a dockerfile. 
Instead, the file system and base image are built by running a few commands manually. 
If you want to know more, try the commands in 
https://servicesblog.redhat.com/2019/10/09/say-hello-to-buildah-podman-and-skopeo/[Say “Hello” to Buildah, Podman, and Skopeo].

Make sure you have already installed the container-tools module. 

== start building a new image

Carry out these commands as root. 

Most of this works fine as a non-root user, but there are a few technical headaches. 
To find out more about rootless containers, check out 
https://www.redhat.com/sysadmin/rootless-podman-makes-sense[Running rootless Podman as a non-root user]. 
And for a description of how a rootless container works, have a look at 
https://www.redhat.com/sysadmin/behind-scenes-podman[What happens behind the scenes of a rootless Podman container?]


[source,shell]
----
[nick@guest3 ~]$ sudo su -
[sudo] password for nick: 
Last login: Thu Aug  6 12:39:14 EDT 2020 on pts/0
[root@guest3 ~]# 
----

Check before. There are no images yet, and no containers built from those images. 

[source,shell]
----
[root@guest3 ~]# buildah images
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
[root@guest3 ~]# 
[root@guest3 ~]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
[root@guest3 ~]# 
----

Start building a new root file system. 

This creates a new container. 
List this new container with `buildah containers`. 
If you want to start again, remove it with `buildah rm working-container`.

[source,shell]
----
[root@guest3 ~]# buildah from scratch
working-container
[root@guest3 ~]# 
[root@guest3 ~]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
b7e26ec492d1     *                  scratch                          working-container
[root@guest3 ~]#  
----

File systems are stored in the directory /var/lib/containers/storage/overlay-containers/.

Mount this new root file system and copy the path. 
We need this later. 

To unmount it, change `mount` to `umount`.

[source,shell]
----
[root@guest3 ~]# MOUNT_DIR=$(buildah mount working-container)
[root@guest3 ~]# 
[root@guest3 ~]# echo $MOUNT_DIR
/var/lib/containers/storage/overlay/bf033e812dd6b65a1e4a587b6a6b3ea54841e03fcced3fb8e4094e0946d3e631/merged
[root@guest3 ~]# 
----

== install RPM modules 

Use this dnf command to install the RPM packages. 
The command only names 6 packages, but 280 packages are required when all the dependencies are worked out.  

[source,shell]
----
dnf install \
  --installroot=$MOUNT_DIR \
  --releasever=/  \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nocontexts \
  --setopt=module_platform_id=platform:el8 \
  --assumeyes  \
  bash coreutils perl dnf iproute vi
----

Clear some space by removing cached data.

[source,shell]
----
[root@guest3 ~]# dnf clean all  --installroot $MOUNT_DIR  --releasever=/
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
26 files removed
[root@guest3 ~]# 
----


== install perl modules 

Convince perl to install in the new file system using the chroot command. 

The new file system doesn't have anything clever like DNS, so 
start by editing the hosts file. 

[source,shell]
----
[root@guest3 ~]# chroot $MOUNT_DIR
bash-4.4# echo "151.101.130.217 cpanmin.us" >> /etc/hosts
bash-4.4# echo "151.101.62.217 cpan.metacpan.org" >> /etc/hosts
bash-4.4# 
----

Install mojolicious. 

[source,shell]
----
bash-4.4# curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0  2067k      0 --:--:-- --:--:-- --:--:-- 2067k
--> Working on Mojolicious
Fetching https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-8.57.tar.gz ... OK
Configuring Mojolicious-8.57 ... OK
Building Mojolicious-8.57 ... OK
Successfully installed Mojolicious-8.57
1 distribution installed
bash-4.4# 
----

Configure a web service. 

The command to start this new web service is `/usr/local/bin/morbo /hello.pl`. 
The _morbo_ command starts a web server - this file was installed along with mojolicious. 
The _hello.pl_ file is created here. 

[source,shell]
----
bash-4.4# echo "use Mojolicious::Lite;
> get '/' => {text => 'I ♥ Mojolicious!'};
> app->start;" > hello.pl
bash-4.4# 
----

That's it. We're done with the chroot. 

[source,shell]
----
bash-4.4# exit
exit
[root@guest3 ~]# 
----

== finish the image

Set the default command to run to _/bin/bash_. 
This isn't what we'll use below.

Add a label. 
After the image is created, you can see this label using the command `podman inspect localhost/myperl`.

[source,shell]
----
[root@guest3 ~]# buildah config --cmd /bin/bash working-container
[root@guest3 ~]# 
[root@guest3 ~]# buildah config --label name=myperlservice working-container
[root@guest3 ~]# 
----

That's it. 
Unmount the file system and create the image. 

[source,shell]
----
[root@guest3 ~]# buildah unmount working-container
b7e26ec492d14eef0bd10c576a73168ef359be819c60a7ddd4ee2f6165f2260a
[root@guest3 ~]# 
[root@guest3 ~]# buildah commit working-container myperl
Getting image source signatures
Copying blob 46b9422120aa done  
Copying config 1cca4b34f6 done  
Writing manifest to image destination
Storing signatures
1cca4b34f6abb293ef53e36546df1036d435c3df5894989d098b37900fe7f587
[root@guest3 ~]# 
[root@guest3 ~]# buildah images
REPOSITORY         TAG      IMAGE ID       CREATED          SIZE
localhost/myperl   latest   1cca4b34f6ab   41 seconds ago   547 MB
[root@guest3 ~]# 
----

The `skopeo` command works with images and registries. 

Use skopeo to display the configuration of our new container. 
The output is JSON. 
There's also a warning that is safe to ignore. 

[source,shell]
----
[root@guest3 ~]# skopeo inspect containers-storage:localhost/myperl
WARN[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
{
    "Name": "localhost/myperl",
    "Digest": "sha256:ad1cdb93acc4cb1ff1be777e3a2f32d7fcdb2b463186835d9e8b8c8872da07cf",
    "RepoTags": [],
    "Created": "2020-08-08T13:25:48.158373762Z",
    "DockerVersion": "",
    "Labels": {
        "io.buildah.version": "1.14.9",
        "name": "myperlservice"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:46b9422120aa6fa311f055098b780cba442ecf7f7c26c2c5735d6cd28a8dcd42"
    ],
    "Env": null
}
[root@guest3 ~]# 
----



== run with podman 

Check there are no containers, either running or stopped. 

[source,shell]
----
[root@guest3 ~]# podman ps -a
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
[root@guest3 ~]# 
----

Create a new container. 

The name of this new container is mojoservice. 
We've already created a repo name and a label name, and now we add a container name.

* The image repo is named "localhost/myperl".
* The "name" label in the config is "myperlservice". You can see this in the `skopeo` output above.
* The container name is "mojoservice". The `podman ps` command below shows this. 

This is the command to create a container. 
The last line is the command that runs our web service. 

[source,shell]
----
podman run \
  -p 3000:3000 \
  --detach \
  --name mojoservice \
  localhost/myperl \
  /usr/local/bin/morbo /hello.pl
----

Start a container and check. 

[source,shell]
----
[root@guest3 ~]# podman run -p 3000:3000 --detach --name mojoservice localhost/myperl /usr/local/bin/morbo /hello.pl
0ac2718c35df066bd8cf4da2d9992ed20d734e2b7c74cb955b42563237cd7a00
[root@guest3 ~]# 
[root@guest3 ~]# podman ps -a
CONTAINER ID  IMAGE                    COMMAND               CREATED        STATUS            PORTS                   NAMES
0ac2718c35df  localhost/myperl:latest  /usr/local/bin/mo...  5 seconds ago  Up 4 seconds ago  0.0.0.0:3000->3000/tcp  mojoservice
[root@guest3 ~]# 
----

Don't be distracted by the word pod in podman. 
This command runs a container, not a pod. 
To find out more about pods and containers, read 
https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods/[Podman: Managing pods and containers in a local container runtime].

You can see the process responsible for this pod. 
It's an absolutely huge `conmon` command with 50 options, and no less than 1700 characters long. 
Luckily this is all created behind the scenes, and you don't have to understand any of this. 

[source,shell]
----
[root@guest3 ~]# ps -fwwC conmon
UID          PID    PPID  C STIME TTY          TIME CMD
root        1744       1  0 09:31 ?        00:00:00 /usr/bin/conmon --api-version 1 -s -c 635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5 -u 635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5 -r /usr/bin/runc -b /var/lib/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata -p /var/run/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/pidfile -l k8s-file:/var/lib/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/ctr.log --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket --log-level error --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/var/run/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/oci-log --conmon-pidfile /var/run/containers/storage/overlay-containers/635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/containers/storage --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 635ee754fd2ff25990ae1cd77ed4e89cccdb4eeb5b5aad75eab23463826e2de5
[root@guest3 ~]# 
----


Does it work? 
Does the web service in the container respond?

It could do with an extra newline, but yes, all good. 

[source,shell]
----
[root@guest3 ~]# curl http://localhost:3000
I ♥ Mojolicious![root@guest3 ~]# 
----

Stop the new container. 

[source,shell]
----
[root@guest3 ~]# podman stop mojoservice
0ac2718c35df066bd8cf4da2d9992ed20d734e2b7c74cb955b42563237cd7a00
[root@guest3 ~]# 
----

If you want to get rid of the new container and image, 
clean up with `podman rm mojoservice` and `podman rmi localhost/myperl`.

== next steps 

Schedule this container to run every time the system boots up. 
This requires systemd configuration. 



