= DNS with Bind 9 
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 01-12-2020

https://www.isc.org/bind/[ISC Bind]

Install Bind.
Reconfigure it to answer queries from the network. 
Tell Bind to be authoritative on the silvan.uk domain, so Bind answers queries about silvan.uk and forwards all other queries to the home network's DNS server. 

This is a simple config that does not cover anything fancy like DNSSEC or split DNS. 


public network - 
  Gateway serves DHCP, DNS 

.utility1 network 
....
+---------------------------------------+
|                                       |
| public gateway                        |
+-+-------------------------------------+
  |
  | public network 
  | 192.168.1.0/24
  |
+-+-------------------------------------+
|enp1s0  utility1.lab.example.com       |
|                                       |
+---------------------------------------+
....


== bind 

[source,shell]
----
dnf install bind bind-utils 
----

before 

[source,shell]
----
[root@utility1 ~]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@utility1 ~]# 
----

enable and start 

[source,shell]
----
[root@utility1 ~]# systemctl enable named
Created symlink /etc/systemd/system/multi-user.target.wants/named.service → /usr/lib/systemd/system/named.service.
[root@utility1 ~]# systemctl start named
[root@utility1 ~]# 
----

after 

[source,shell]
----
[root@utility1 named]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; vendor prese>
   Active: active (running) since Wed 2020-12-02 16:55:02 GMT; 3h 55min ago
  Process: 6703 ExecStart=/usr/sbin/named -u named -c ${NAMEDCONF} $OPTIONS (co>
  Process: 6700 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "y>
 Main PID: 6705 (named)
    Tasks: 5 (limit: 23328)
   Memory: 59.5M
   CGroup: /system.slice/named.service
           └─6705 /usr/sbin/named -u named -c /etc/named.conf

Dec 02 16:55:02 utility1.silvan.uk named[6705]: zone 0.in-addr.arpa/IN: loaded >
Dec 02 16:55:02 utility1.silvan.uk named[6705]: zone 1.0.0.127.in-addr.arpa/IN:>
Dec 02 16:55:02 utility1.silvan.uk named[6705]: zone localhost/IN: loaded seria>
Dec 02 16:55:02 utility1.silvan.uk named[6705]: zone 1.0.0.0.0.0.0.0.0.0.0.0.0.>
Dec 02 16:55:02 utility1.silvan.uk named[6705]: zone localhost.localdomain/IN: >
Dec 02 16:55:02 utility1.silvan.uk named[6705]: all zones loaded
Dec 02 16:55:02 utility1.silvan.uk named[6705]: running
Dec 02 16:55:02 utility1.silvan.uk systemd[1]: Started Berkeley Internet Name D>
Dec 02 16:55:02 utility1.silvan.uk named[6705]: managed-keys-zone: Key 20326 fo>
Dec 02 16:55:02 utility1.silvan.uk named[6705]: resolver priming query complete
[root@utility1 named]# 
----

== forwarding 

before 

[source,shell]
----
[root@utility1 ~]# host www.google.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[root@utility1 ~]# 
----

[source,shell]
----
[root@utility1 ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home silvan.uk
nameserver 192.168.1.254
[root@utility1 ~]# 
----


== listen to all interfaces 

The machine has two network interfaces - _lo_ and _enp1s0_.

[source,shell]
----
[root@utility1 ~]# ip addr | grep 'inet '
    inet 127.0.0.1/8 scope host lo
    inet 192.168.1.217/24 brd 192.168.1.255 scope global dynamic noprefixroute enp1s0
[root@utility1 ~]# 
----

The DNS server is only listening to _lo_, the loopback interface. 
127.0.0.1 is the loopback interface's IPv4 address and [::1] is the IPv6 address. 

[source,shell]
----
[root@utility1 named]# ss -tl  '( dport = :domain or sport = :domain )'
State     Recv-Q    Send-Q       Local Address:Port         Peer Address:Port   
LISTEN    0         10               127.0.0.1:domain            0.0.0.0:*      
LISTEN    0         10                   [::1]:domain               [::]:*      
[root@utility1 named]# 
----

The config file contains https://bind9.readthedocs.io/en/latest/reference.html?highlight=listen-on#interfaces[listen-on] options.
These tell Bind to listen only to the loopback interface, so the rest of the network can't talk to it. 

[source,shell]
----
[root@utility1 ~]# grep listen-on /etc/named.conf 
  listen-on port 53 { 127.0.0.1; };
	listen-on-v6 port 53 { ::1; };
[root@utility1 ~]# 
----

Make Bind listen to the network address. 
This requires changing both the Bind config and firewalld's config. 

The IPv4 default is to listen to all interfaces. 
The IPv6 default is not to listen. 

Comment out the IPv4 line. 

[source,shell]
----
  #listen-on port 53 { 127.0.0.1; };
  listen-on-v6 port 53 { ::1; };
----

Check the change is OK. 
This is good. 

[source,shell]
----
[root@utility1 ~]# named-checkconf /etc/named.conf
[root@utility1 ~]# 
----

This is bad. The problem here is a typo: *~* instead of *#*. 

[source,shell]
----
[root@utility1 ~]# named-checkconf /etc/named.conf
/etc/named.conf:11: unknown option '~listen-on'
[root@utility1 ~]# 
----


Reload the configuration. 

[source,shell]
----
[root@utility1 ~]# systemctl reload named
[root@utility1 ~]# 
----

Bind starts listening to the IPv4 address 192.168.1.217.

[source,shell]
----
[root@utility1 ~]# ss -tln | grep :53
LISTEN    0         10           192.168.1.217:53               0.0.0.0:*       
LISTEN    0         10               127.0.0.1:53               0.0.0.0:*       
LISTEN    0         10                   [::1]:53                  [::]:*       
[root@utility1 ~]# 
----

Check. 

[source,shell]
----
[root@utility1 ~]# host www.google.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[root@utility1 ~]# 
----


== allow requests through the firewall 

Check from host1. 
Nothing happens, then the attempt times out. 

[source,shell]
----
[nick@host1 ~]$ host www.google.com 192.168.1.217
...(big pause)...
;; connection timed out; no servers could be reached
[nick@host1 ~]$ 
----

Edit the firewall on utility1. 

[source,shell]
----
[root@utility1 ~]# firewall-cmd --add-service=dns
success
[root@utility1 ~]# firewall-cmd --add-service=dns --permanent
success
[root@utility1 ~]# 
----

Try again from host1. 
This time the reply is instant, but it's refused. 
Bind has a security feature that only allows queries from localhost. 
That's the next thing to change. 


[source,shell]
----
[nick@host1 ~]$ host www.google.com 192.168.1.217
Using domain server:
Name: 192.168.1.217
Address: 192.168.1.217#53
Aliases: 

Host www.google.com not found: 5(REFUSED)
[nick@host1 ~]$ 
----


== tell Bind to allow requests from the network 

Bind has many https://bind9.readthedocs.io/en/latest/reference.html?highlight=listen-on#access-control[access control] options, and most of them start with _allow-_.
The only one included in the default config file is _allow-query_. 

[source,shell]
----
[root@utility1 ~]# grep allow- /etc/named.conf 
	allow-query     { localhost; };
[root@utility1 ~]# 
----

the default is to allow all queries, so comment out the statement. 

[source,shell]
----
	#allow-query     { localhost; };
----

Reload the configuration with _systemctl reload named_.

Check again from host1. 


[source,shell]
----
[nick@host1 ~]$ host www.google.com 192.168.1.217
Using domain server:
Name: 192.168.1.217
Address: 192.168.1.217#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[nick@host1 ~]$ 
----

Bind is now talking to the network. 
The next thing to do is give Bind a zone to manage. 



== add a zone file

A zone is a set of names and addresses for a name like www.silvan.uk. 
Add a zone file that describes silvan.uk. 

Bind already has some zones defined. 
The details are in files in the /var/named/ directory, such as named.ca which lists servers for the root domain. 
Bind's config has _zone_ options which tell Bind where these files are. 
One zone option is in /etc/named.conf and more are in /etc/named.rfc1912.zones
https://tools.ietf.org/html/rfc1912[RFC 1912] is about "Common DNS Operational and Configuration Errors" and says "certain zones should always be present", so this config file ticks that box. 


[source,shell]
----
[root@utility1 ~]# cd /var/named/
[root@utility1 named]# 
[root@utility1 named]# vi silvan.uk-records
----


These are the records. 
The file is spaced out to look more like a table (that's another suggestion from RFC 1912). 

[source,shell]
----
$TTL 3H
@    IN SOA    @ root.silvan.uk (
                    0    ; serial
                    1D    ; refresh
                    1H    ; retry
                    1W    ; expire
                    3H )    ; minimum
; these records are names and addresses for silvan.uk
             IN NS   dns1
             A       192.168.1.217
             AAAA    2a00:23c8:1d05:1e00:5054:ff:fe00:1
; these records are names and addresses for (HOST).silvan.uk
dns1         IN A    192.168.1.217
satellite1   IN A    192.168.1.214
satellite1.lab   IN A    192.168.1.214
utility1     IN A    192.168.1.217
----


[source,shell]
----
$TTL 3H
@    IN SOA    @ root.silvan.uk (
                    0    ; serial
                    1D    ; refresh
                    1H    ; retry
                    1W    ; expire
                    3H )    ; minimum
            IN NS   dns1.silvan.uk.
217         IN PTR dns1.silvan.uk.
214         IN PTR satellite1.silvan.uk.
214         IN PTR satellite1.lab.silvan.uk.
217         IN PTR utility1.silvan.uk.
----



[source,shell]
----
[root@utility1 named]# ls -la 
total 28
drwxrwx--T.  5 root  named  177 Dec  3 17:57 .
drwxr-xr-x. 21 root  root  4096 Dec  2 16:50 ..
-rw-r-----.  1 root  root   336 Dec  3 17:57 192.168.1-records
drwxrwx---.  2 named named   23 Dec  2 16:55 data
drwxrwx---.  2 named named   60 Dec  3 17:57 dynamic
-rw-r-----.  1 root  named 2253 Aug 21 11:12 named.ca
-rw-r-----.  1 root  named  152 Aug 21 11:12 named.empty
-rw-r-----.  1 root  named  152 Aug 21 11:12 named.localhost
-rw-r-----.  1 root  named  168 Aug 21 11:12 named.loopback
-rw-r-----.  1 root  root   527 Dec  3 17:55 silvan.uk-records
drwxrwx---.  2 named named    6 Aug 21 11:12 slaves
[root@utility1 named]# 
----

Change the group to match the other files. 
[source,shell]
----
[root@utility1 named]# chown .named silvan.uk-records 192.168.1-records 
[root@utility1 named]# 
----

No need to change the SELinux file type - all the files are _named_zone_t_.


=== more config 

Tell Bind where the new zone records are. 
Add these options to the bottom of /etc/named.conf.

[source,shell]
----
zone "silvan.uk" IN {
  type master;
  file "silvan.uk-records";
};

zone "1.168.192.in-addr.arpa" IN {
  type master;
  file "192.168.1-records";
};
----


Check the SOA records. 

[source,shell]
----
[root@utility1 named]# host -t SOA silvan.uk localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

silvan.uk has SOA record silvan.uk. root.silvan.uk.silvan.uk. 0 86400 3600 604800 10800
[root@utility1 named]# 
[root@utility1 named]# host -t SOA 1.168.192.in-addr.arpa localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

1.168.192.in-addr.arpa has SOA record 1.168.192.in-addr.arpa. root.silvan.uk.1.168.192.in-addr.arpa. 0 86400 3600 604800 10800
[root@utility1 named]#
----

Check the NS records. 

[source,shell]
----
[root@utility1 named]# host -t NS silvan.uk localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

silvan.uk name server dns1.silvan.uk.
[root@utility1 named]# 
[root@utility1 named]# host -t NS 1.168.192.in-addr.arpa localhost 
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

1.168.192.in-addr.arpa name server dns1.silvan.uk.
[root@utility1 named]# 
----

Check one of the A records and the matching PTR record. 


[source,shell]
----
[root@utility1 named]# host utility1.silvan.uk localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

utility1.silvan.uk has address 192.168.1.217
[root@utility1 named]# host 192.168.1.217 localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

217.1.168.192.in-addr.arpa domain name pointer dns1.silvan.uk.
217.1.168.192.in-addr.arpa domain name pointer utility1.silvan.uk.
[root@utility1 named]# 
----


== tell NetworkManager to use Bind 9

Run nmcli commands to tell NetworkManager to use the local DNS service.

NetworkManager uses the home network DNS service. 
It was told to do this by DHCP. 

[source,shell]
----
[root@utility1 named]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home silvan.uk
nameserver 192.168.1.254
[root@utility1 named]# 
[root@utility1 named]# nmcli 
...
DNS configuration:
        servers: 192.168.1.254
        domains: home
        interface: enp1s0
...
[root@utility1 named]# 
----

NetworkManager has a quite a few options for DNS. 
The settings in this list that are lowercase can be changed. 
The upper case settings (the ones spelled with CAPITAL LETTERS) can't - these show what was defined for the current session. 

[source,shell]
----
[root@utility1 named]# nmcli con show enp1s0 | grep dns
connection.mdns:                        -1 (default)
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.ignore-auto-dns:                   no
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.ignore-auto-dns:                   no
[root@utility1 named]# 
[root@utility1 named]# nmcli con show enp1s0 | grep domain
DHCP4.OPTION[2]:                        domain_name = home
DHCP4.OPTION[3]:                        domain_name_servers = 192.168.1.254
DHCP4.OPTION[7]:                        requested_domain_name = 1
DHCP4.OPTION[8]:                        requested_domain_name_servers = 1
DHCP4.OPTION[9]:                        requested_domain_search = 1
DHCP4.OPTION[13]:                       requested_nis_domain = 1
DHCP6.OPTION[1]:                        dhcp6_domain_search = home
[root@utility1 named]# 
----

Change the IPv4 settings. 

[source,shell]
----
[root@utility1 named]# nmcli con mod enp1s0 ipv4.dns 127.0.0.1
[root@utility1 named]# 
[root@utility1 named]# nmcli con mod enp1s0 ipv4.ignore-auto-dns yes
[root@utility1 named]# 
----

Apply the changes. 

[source,shell]
----
[root@utility1 named]# nmcli con up enp1s0
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/3)
[root@utility1 named]# 
----

Check the resolver config file. 

[source,shell]
----
[root@utility1 named]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home silvan.uk
nameserver 127.0.0.1
[root@utility1 named]# 
----

Check Bind is now the default choice. 

[source,shell]
----
[root@utility1 named]# host silvan.uk
silvan.uk has address 192.168.1.217
silvan.uk has IPv6 address 2a00:23c8:1d05:1e00:5054:ff:fe00:1
[root@utility1 named]# 
----

