= set up the guest1 OS 
Nick Hardiman <nhardima@redhat.com>
:source-highlighter: pygments
:toc:
:revdate: 28-11-2020


Carry out some first-run sysadmin on the new machine. 

Many things are already configured, like SSH daemon, NTP, hostname and first interface. 

== IP address and DNS 

The first network interface on _guest1_ is connected to the home network. 
It has probably been given an IP address by the DHCP server built into the ISP router. 

Virsh can't tell you because it isn't managing DHCP for this interface. The _virsh net-dhcp-leases pubbr0_ won't work. 

Find the address. 

* Connect to the console, log into the machine, run _ip addr_ and copy the IP address.
This is the easiest way. 
* Find out what IP address the home DHCP server allocated.  
This depends on what your home network equipment is. 
* Watch network traffic. Run _sudo tcpdump -nn ether host 52:54:00:00:00:01_ on _host1_ and wait for something to happen. 
This is proper network admin. 

== connect using SSH 

Copy your public key for easier and safer login. 

[source,bash]
....
ssh-copy-id nick@guest1
....

SSH from your workstation to the machine. 

== harden security  

Anyone on the home network can get at this machine, so security is an issue. 

Disable root login. 

* Use the root account. 
* Edit /etc/ssh/sshd_config.
* Change PermitRootLogin to no.
* Restart the service with _systemctl reload sshd.service_


== update packages 

The kickstart process registered this machine with Red Hat and entitled it to receive updates. 

[source,bash]
....
[root@guest1 ~]# dnf -y update
...
[root@guest1 ~]# systemctl reboot
Connection to guest1 closed by remote host.
Connection to guest1 closed.
workstation:~ nick$ 
....

Wait a minute and log in again. 

== enable the second interface 

Only one of the two network interfaces, enp1s0 and enp2s0, is up.

[source,bash]
....
[nick@guest1 ~]$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.217/24 brd 192.168.1.255 scope global dynamic noprefixroute enp1s0
       valid_lft 86169sec preferred_lft 86169sec
    inet6 2a00:23c8:1d05:1e00:8750:d339:eb3c:f6b5/64 scope global dynamic noprefixroute 
       valid_lft 315359973sec preferred_lft 315359973sec
    inet6 fdaa:bbcc:ddee:0:9e7f:3e3d:a419:1886/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::5be1:424b:e11b:afe3/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:00:00:02 brd ff:ff:ff:ff:ff:ff
[nick@guest1 ~]$ 
....

NetworkManager created a configuration to manage enp2s0, but it is not set to start automatically. 

[source,bash]
....
[nick@guest1 ~]$ nmcli con 
NAME    UUID                                  TYPE      DEVICE 
enp1s0  b5220e04-f959-454c-8c89-4b0006f0050a  ethernet  enp1s0 
enp2s0  82d6f9e9-1364-4685-89dd-143c676c946a  ethernet  --     
[nick@guest1 ~]$ 
....

Turn on autoconnect and check again. 

[source,bash]
....
[nick@guest1 ~]$ sudo nmcli con mod enp2s0 connection.autoconnect yes
[sudo] password for nick: 
[nick@guest1 ~]$ 
[nick@guest1 ~]$ nmcli con 
NAME    UUID                                  TYPE      DEVICE 
enp1s0  b5220e04-f959-454c-8c89-4b0006f0050a  ethernet  enp1s0 
enp2s0  82d6f9e9-1364-4685-89dd-143c676c946a  ethernet  enp2s0 
[nick@guest1 ~]$ 
....

A dnsmasq DHCP server manages IP addresses for this network.
The server issues an IP address to guest1. 

Check the interface. 

[source,bash]
....
[nick@guest1 ~]$ ip addr show dev enp2s0
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:00:00:02 brd ff:ff:ff:ff:ff:ff
    inet 192.168.126.28/24 brd 192.168.126.255 scope global dynamic noprefixroute enp2s0
       valid_lft 3547sec preferred_lft 3547sec
    inet6 fe80::12d7:778d:1fe6:386f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[nick@guest1 ~]$ 

Open another terminal. 

Check on _host1_. 

[nick@host1 ~]$ sudo virsh net-dhcp-leases privbr0 
 Expiry Time           MAC address         Protocol   IP address          Hostname   Client ID or DUID
-----------------------------------------------------------------------------------------------------------
 2021-01-12 18:40:32   52:54:00:00:00:02   ipv4       192.168.126.28/24   guest1     01:52:54:00:00:00:02

[nick@host1 ~]$ 
....
