= use Apache for cgroup experiments
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 01-07-2020

Install Apache.
Set up modules to provide information. 


== install 

[source,shell]
----
[root@guest1 ~]# dnf install httpd 
Updating Subscription Management repositories.
Last metadata expiration check: 1:26:45 ago on Mon 01 Feb 2021 19:17:55 GMT.
Dependencies resolved.
================================================================================
 Package            Arch   Version       Repository                        Size
================================================================================
Installing:
 httpd              x86_64 2.4.37-30.module+el8.3.0+7001+0766b9e7
                                         rhel-8-for-x86_64-appstream-rpms 1.4 M
Installing dependencies:
 httpd-filesystem   noarch 2.4.37-30.module+el8.3.0+7001+0766b9e7
                                         rhel-8-for-x86_64-appstream-rpms  37 k
 mailcap            noarch 2.1.48-3.el8  rhel-8-for-x86_64-baseos-rpms     39 k
 mod_http2          x86_64 1.15.7-2.module+el8.3.0+7670+8bf57d29
                                         rhel-8-for-x86_64-appstream-rpms 154 k
 redhat-logos-httpd noarch 81.1-1.el8    rhel-8-for-x86_64-baseos-rpms     26 k

Transaction Summary
================================================================================
Install  5 Packages

Total download size: 1.6 M
Installed size: 4.7 M
Is this ok [y/N]: 
----

Copies executables, logs, content and config. 
Config includes many systemd files.


== systemd units

The unit file httpd.service starts and stops apache.

There is also a socket unit file and drop-in directories. 
The httpd@.service file is an "instantiated template service".
For more information, run  `man httpd.service`.


[source,shell]
----
[root@guest1 ~]# ls -1dF /usr/lib/systemd/system/httpd*
/usr/lib/systemd/system/httpd.service
'/usr/lib/systemd/system/httpd@.service'
/usr/lib/systemd/system/httpd.service.d/
/usr/lib/systemd/system/httpd.socket
/usr/lib/systemd/system/httpd.socket.d/
[root@guest1 ~]# 
----

View the unit configuration. 

[source,shell]
----
[root@guest1 ~]# systemctl cat httpd.service
# /usr/lib/systemd/system/httpd.service
# See httpd.service(8) for more information on using the httpd service.

# Modifying this file in-place is not recommended, because changes
# will be overwritten during package upgrades.  To customize the
# behaviour, run "systemctl edit httpd" to create an override unit.

# For example, to pass additional options (such as -D definitions) to
# the httpd binary at startup, create an override unit (as is done by
# systemctl edit) and enter the following:

#       [Service]
#       Environment=OPTIONS=-DMY_DEFINE

[Unit]
Description=The Apache HTTP Server
Wants=httpd-init.service
After=network.target remote-fs.target nss-lookup.target httpd-init.service
Documentation=man:httpd.service(8)

[Service]
Type=notify
Environment=LANG=C

ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND
ExecReload=/usr/sbin/httpd $OPTIONS -k graceful
# Send SIGWINCH for graceful stop
KillSignal=SIGWINCH
KillMode=mixed
PrivateTmp=true

[Install]
WantedBy=multi-user.target

[root@guest1 ~]# 
----


== configure apache

Tell systemd to run apache. 

Customize the config. 

Change the port in the main config file. 
This file is /etc/httpd/conf/httpd.conf.


=== use port 8080 

By default, apache listens to port 80. 
This port will be listened to by haproxy later. 

Change the port to 8080. 

[source,shell]
----
[root@guest1 ~]# vi /etc/httpd/conf/httpd.conf 
----

Find the Listen line. 

[source,shell]
----
Listen 80
----

Change it. 

[source,shell]
----
Listen 8080
----



=== systemd 

Start the service.  

[source,shell]
----
systemctl start httpd.service 
systemctl enable httpd.service 
/etc/systemd/system/multi-user.target.wants/httpd.service → /usr/lib/systemd/system/httpd.service
----

=== check apache 

Apache manages its own logging. 
When Apache starts, it creates two log files. 

[source,shell]
----
[root@guest1 ~]# ls /var/log/httpd/
access_log  error_log
[root@guest1 ~]# 
----

Apache runs half a dozen processes. 
One parent, four children. 
Each child has many threads. 

[source,shell]
----
[root@guest1 ~]# ps -fC httpd
UID          PID    PPID  C STIME TTY          TIME CMD
root      256917       1  0 21:04 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    256918  256917  0 21:04 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    256919  256917  0 21:04 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    256920  256917  0 21:04 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
apache    256921  256917  0 21:04 ?        00:00:00 /usr/sbin/httpd -DFOREGROUND
[root@guest1 ~]# 
----

The pstree utility can display a simple tree of processes. 
Install pstree with `dnf install psmisc`.

List the children of httpd parent process. 
The parent is the one owned by root. 

[source,shell]
----
[root@guest1 ~]# pstree -cT 256917
httpd─┬─httpd
      ├─httpd
      ├─httpd
      └─httpd
[root@guest1 ~]# 
----

Get the home page. 
It's a big page, so display the HTTP headers and the top of the page only. 

[source,shell]
----
[root@guest1 ~]# curl --head localhost:8080 
HTTP/1.1 403 Forbidden
Date: Mon, 01 Feb 2021 21:20:14 GMT
Server: Apache/2.4.37 (Red Hat Enterprise Linux)
Last-Modified: Mon, 15 Jun 2020 11:49:07 GMT
ETag: "f91-5a81e03a232c0"
Accept-Ranges: bytes
Content-Length: 3985
Content-Type: text/html; charset=UTF-8

[root@guest1 ~]# 
[root@guest1 ~]# curl --silent localhost:8080 | head -n 5
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
		<title>Test Page for the Apache HTTP Server on Red Hat Enterprise Linux</title>
[root@guest1 ~]# 
----

The code is 403, forbidden. 
There is no content to display, so we're getting an error page instead. 

[source,shell]
----
[root@guest1 ~]# ls /var/www/html/
[root@guest1 ~]# 
----


== open the firewall 

Clients on the network can't see this web server. 
Open the firewall. 

[source,shell]
----
firewall-cmd --add-port 8080/tcp
firewall-cmd --add-port 8080/tcp --permanent
----



