= tell NetworkManager to use Bind 
Nick Hardiman <nhardima@redhat.com>
:source-highlighter: pygments
:revdate: 11-01-2021

NetworkManager uses the home network's name service, not the new name service on _guest1_.
Run https://developer.gnome.org/NetworkManager/stable/nmcli.html[nmcli] commands to tell NetworkManager to use the local DNS service.


== the current setup 

NetworkManager uses two nameservers - one on the home network and one provided by dnsmasq. 
It was told to do this by DHCP, when it brought up the two interfaces enp1s0 and enp2s0.

[source,shell]
----
[root@guest1 named]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home lab.example.com
nameserver 192.168.1.254
nameserver 192.168.126.1
[root@guest1 named]# 
[root@guest1 named]# nmcli 
...
DNS configuration:
        servers: 192.168.1.254
        domains: home
        interface: enp1s0
...
[root@guest1 named]# 
----


== NetworkManager DNS options 

NetworkManager has a quite a few options for DNS. 
The settings in this list that are lowercase can be changed. 
The upper case settings (the ones spelled with CAPITAL LETTERS) can't - these show what was defined for the current session. 

[source,shell]
----
[root@guest1 named]# nmcli con show enp1s0 | grep dns
connection.mdns:                        -1 (default)
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.ignore-auto-dns:                   no
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.ignore-auto-dns:                   no
[root@guest1 named]# 
[root@guest1 named]# nmcli con show enp1s0 | grep domain
DHCP4.OPTION[2]:                        domain_name = home
DHCP4.OPTION[3]:                        domain_name_servers = 192.168.1.254
DHCP4.OPTION[7]:                        requested_domain_name = 1
DHCP4.OPTION[8]:                        requested_domain_name_servers = 1
DHCP4.OPTION[9]:                        requested_domain_search = 1
DHCP4.OPTION[13]:                       requested_nis_domain = 1
DHCP6.OPTION[1]:                        dhcp6_domain_search = home
[root@guest1 named]# 
----


== change settings for enp1s0

Change the IPv4 settings. 

[source,shell]
----
[root@guest1 named]# nmcli con mod enp1s0 ipv4.dns 127.0.0.1
[root@guest1 named]# 
[root@guest1 named]# nmcli con mod enp1s0 ipv4.ignore-auto-dns yes
[root@guest1 named]# 
----

Apply the changes. 

[source,shell]
----
[root@guest1 named]# nmcli con up enp1s0
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/3)
[root@guest1 named]# 
----

Check the resolver config file. 

[source,shell]
----
[root@guest1 named]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home lab.example.com
nameserver 127.0.0.1
[root@guest1 named]# 
----


== change settings for enp2s0


[source,shell]
----
nmcli con mod enp2s0 ipv4.ignore-auto-dns yes
nmcli con up enp1s0
----

== check your work 

Check Bind is now the default choice. 

[source,shell]
----
[root@guest1 named]# host lab.example.com
lab.example.com has address 192.168.1.217
lab.example.com has IPv6 address 2a00:23c8:1d05:1e00:5054:ff:fe00:1
[root@guest1 named]# 
----

