= copy an image using libguestfs-tools 
Nick Hardiman <nhardima@redhat.com>
:source-highlighter: pygments
:toc: 
:revdate: 23-11-2020

Use rhel-8.3-x86_64-kvm.qcow2 as a golden image.
A new virtual machine is built by copying the golden image and customizing the copy.

[source,console]
----
sudo dnf install libguestfs-tools  # for virt-resize and virt-customize
----

== examine the golden image 

virt-inspector rhel-8.3-x86_64-kvm.qcow2
produces a vast amount of data. 

List partitions. 

[source,console]
----
[root@host1 images]# virt-filesystems --parts --add rhel-8.3-x86_64-kvm.qcow2  
/dev/sda1
/dev/sda2
/dev/sda3
[root@host1 images]# 
----

Take a closer look at those partitions by listing file systems. 
The root file system is _/dev/sda3_, which is is nearly 10GiB in size (10629414912 bytes). 

[source,console]
----
[root@host1 images]# virt-filesystems --filesystems --long --add rhel-8.3-x86_64-kvm.qcow2 
Name       Type        VFS   Label  Size         Parent
/dev/sda2  filesystem  vfat  -      104857600    -
/dev/sda3  filesystem  xfs   root   10629414912  -
[root@host1 images]# 
----



== create an empty volume  

Don't use the original image file for creating a machine. 
It can remain as the backup file. 
Make a copy and edit that instead.

Create an empty qcow2 image file. 
The command _virsh vol-create-as_ needs a pool name, the new file name and how big the volume should be. 
If you can't remember your pool name, run _virsh pool-list_ to check.

[source,console]
----
[root@host1 images]# MY_COPY=guest2.qcow2
[root@host1 images]# SIZE=300G
[root@host1 images]# virsh vol-create-as --format qcow2 images $MY_COPY $SIZE
Vol guest2 created

[root@host1 images]# 
----

This huge 300G volume is contained in a very small 1.3G file. 
This is a sparse volume. 
The whole 300 GiB is not allocated now - space is added later, when it is required.

[source,console]
----
[root@host1 images]# ls -lh
total 1.3G
-rw-r--r--. 1 root root 1.3G Nov 23 16:23 rhel-8.3-x86_64-kvm.qcow2
-rw-------. 1 root root 197K Nov 23 17:01 guest2.qcow2
[root@host1 images]# 
----

=== delete 

If you want to remove this new file and start again, delete it with _virsh vol-delete_. 
Don't use the bash command _rm_ because it removes the file and leaves behind libvirt's configuration about this file. 
The _vol-delete_ command removes both the file and libvirt's config. 

[source,console]
----
[root@host1 images]# virsh vol-delete $MY_COPY --pool images
Vol guest2 deleted

[root@host1 images]# 
----





== fill the empty volume

Fill up the new volume using the _virt_resize_ command. 
This doesn't actually resize one file in-place - it reads one file and overwrites a second file. 
Virt_resize expands the volume in the second file while it's copying.

Libvirt does come with a volume copying command, _virsh vol-clone_. It can make a new copy, but it can't change its size. 

[source,console]
----
[root@host1 images]# MY_COPY=guest2.qcow2
[root@host1 images]# GOLDEN_IMAGE=rhel-8.3-x86_64-kvm.qcow2 
[root@host1 images]# 
[root@host1 images]# virt-resize --expand /dev/sda3 $GOLDEN_IMAGE $MY_COPY 
[   0.0] Examining rhel-8.3-x86_64-kvm.qcow2
**********

Summary of changes:

/dev/sda1: This partition will be left alone.

/dev/sda2: This partition will be left alone.

/dev/sda3: This partition will be resized from 9.9G to 299.9G.  The 
filesystem xfs on /dev/sda3 will be expanded using the ‘xfs_growfs’ 
method.

**********
[   5.7] Setting up initial partition table on guest2.qcow2
[  16.6] Copying /dev/sda1
[  16.7] Copying /dev/sda2
[  16.8] Copying /dev/sda3
 100% ⟦▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒⟧ 00:00
[  27.4] Expanding /dev/sda3 using the ‘xfs_growfs’ method

Resize operation completed with no errors.  Before deleting the old disk, 
carefully check that the resized disk boots and works correctly.
[root@host1 images]# 
----

The file is much bigger now, but still a fraction of its defined size. 

[source,console]
----
[root@host1 images]# ls -lh
total 3.6G
-rw-r--r--. 1 qemu qemu 1.3G Nov 23 16:23 rhel-8.3-x86_64-kvm.qcow2
-rw-------. 1 root root 2.3G Nov 23 17:16 guest2.qcow2
[root@host1 images]# 
----


== customize the KVM image  

This image has no root password and no other accounts, so we can't log in.
Change this and a few other things with the ``virt-customize`` command.

Check out that insecure password. 


[source,console]
----
virt-customize \
  --add            guest2.qcow2  \
  --root-password  password:'x%5ckA-1'  \
  --hostname       guest2.lab.silvan.uk  \
  --timezone       'Europe/London'  \
  --selinux-relabel
----

The command takes a few seconds. ``virt-customize``` prints an activity log, along with seconds elapsed.

[source,console]
----
[nick@host ~]$ virt-customize --add guest-images/guest2.qcow2 --root-password password:'x%5ckA-1' --hostname guest2.lab.example.com
[   0.0] Examining the guest ...
[   4.6] Setting a random seed
[   4.6] Setting the machine ID in /etc/machine-id
[   4.6] Setting the hostname: guest2.lab.example.com
[   4.6] Setting the timezone: Europe/London
[   4.7] Setting passwords
[   5.9] SELinux relabelling
[  18.3] Finishing off
[nick@host ~]$ 
----



