= share directories with NFS
Nick Hardiman
:source-highlighter: pygments
:toc: 
:revdate: 05-12-2020


https://en.wikipedia.org/wiki/Network_File_System[NFS (Network File System)] allows a local directory to be shared by many remote machines. 

Set up an NFS server. 
Use the latest version 4 - this has been around for many years. 

== install 

The core of NFS is built into the kernel. 
The user-space tools to manage NFS are not included in a minimal installation. 

Use the root account. 

Install the NFS utilities package. 

[source,console]
----
[root@guest1 ~]# dnf install nfs-utils
Updating Subscription Management repositories.
Last metadata expiration check: 1:04:57 ago on Mon 18 Jan 2021 09:21:41 GMT.
Dependencies resolved.
====================================================================================================================================
 Package                        Architecture        Version                        Repository                                  Size
====================================================================================================================================
Installing:
 nfs-utils                      x86_64              1:2.3.3-35.el8                 rhel-8-for-x86_64-baseos-rpms              494 k
Installing dependencies:
 gssproxy                       x86_64              0.8.0-16.el8                   rhel-8-for-x86_64-baseos-rpms              118 k
 keyutils                       x86_64              1.5.10-6.el8                   rhel-8-for-x86_64-baseos-rpms               63 k
 libverto-libevent              x86_64              0.3.0-5.el8                    rhel-8-for-x86_64-baseos-rpms               16 k
 python3-pyyaml                 x86_64              3.12-12.el8                    rhel-8-for-x86_64-baseos-rpms              193 k
 quota                          x86_64              1:4.04-10.el8                  rhel-8-for-x86_64-baseos-rpms              214 k
 quota-nls                      noarch              1:4.04-10.el8                  rhel-8-for-x86_64-baseos-rpms               94 k
 rpcbind                        x86_64              1.2.5-7.el8                    rhel-8-for-x86_64-baseos-rpms               70 k

Transaction Summary
====================================================================================================================================
Install  8 Packages

Total download size: 1.2 M
Installed size: 3.7 M
Is this ok [y/N]: 

== configure  

The _/etc/nfs.conf_ file is an https://en.wikipedia.org/wiki/INI_file[INI file]. 
A fresh install has a lot of headings, but only one value (`use-gss-proxy=1`). 
Use `man nfs.conf` to find out more about this file. 

[source,console]
----
[root@guest1 ~]$ grep -v -E '^#' /etc/nfs.conf 
[general]
[exportfs]
[gssd]
use-gss-proxy=1
[lockd]
[mountd]
[nfsdcltrack]
[nfsd]
[statd]
[sm-notify]
[root@guest1 ~]$ 
----




=== use version 4 only

Versions 3 and 4 are enabled. 
Version 4.2 has been around for a few years, so it's safe to keep this one and disable the others. 

[source,console]
----
[root@guest1 ~]# grep vers /etc/nfs.conf 
# reverse-lookup=n
# vers2=n
# vers3=y
# vers4=y
# vers4.0=y
# vers4.1=y
# vers4.2=y
[root@guest1 ~]# 
----

Enable version 4.2.
This is enabled by default, so this change only makes it more obvious. 

This file can be changed by editing it or by using the nfsconf utility. 

[source,console]
----
[root@guest1 ~]$ nfsconf --set nfsd vers4.2 y
[root@guest1 ~]$ 
----

Check.  

[source,console]
----
[root@guest1 ~]$ grep -v -E '^#' /etc/nfs.conf 
...
[nfsd]
vers4.2 = y
[statd]
[sm-notify]
[root@guest1 ~]$ 
----

Disable the older versions. 



=== systemd  

before 

[root@guest1 ~]# systemctl status nfs-server
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@guest1 ~]# 

after 

[source,console]
----
[root@helper pv1]# systemctl status nfs-server
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled; vendor preset: disabled)
  Drop-In: /run/systemd/generator/nfs-server.service.d
           └─order-with-mounts.conf
   Active: active (exited) since Tue 2020-10-20 02:47:34 PDT; 7h ago
  Process: 1477 ExecStart=/bin/sh -c if systemctl -q is-active gssproxy; then systemctl reload gssproxy ; fi (code=exited, status=0/SUCCESS)
  Process: 1420 ExecStart=/usr/sbin/rpc.nfsd (code=exited, status=0/SUCCESS)
  Process: 1414 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 1477 (code=exited, status=0/SUCCESS)

Oct 20 02:47:33 helper systemd[1]: Starting NFS server and services...
Oct 20 02:47:34 helper systemd[1]: Started NFS server and services.
[root@helper pv1]# 
----

== share directories 

=== make directories to share 

[source,console]
----
[root@helper ~]# mkdir /var/nfs
[root@helper ~]# 
[root@helper ~]# cd /var/nfs
[root@helper nfs]# 
[root@helper nfs]# mkdir pv1
[root@helper nfs]# mkdir pv2
[root@helper nfs]# mkdir pv3
[root@helper nfs]# 
----

[source,console]
----
[root@helper nfs]# ls -l
total 0
drwxr-xr-x. 2 root root 6 Oct 20 09:15 pv1
drwxr-xr-x. 2 root root 6 Oct 20 09:15 pv2
drwxr-xr-x. 2 root root 6 Oct 20 09:15 pv3
[root@helper ~]# 
[root@helper nfs]# chmod 777 *
[root@helper nfs]# 
----


=== tell NFS about these directories 

Add config for the new exports. 

[source,console]
----
[root@helper nfs]# vi /etc/exports

/export	*(rw,sync,root_squash)
/var/nfs/pv1	*(rw,sync,root_squash)
/var/nfs/pv2	*(rw,sync,root_squash)
/var/nfs/pv3	*(rw,sync,root_squash)
[root@helper pv1]# 
----

Tell the NFS service about the new exports.

[source,console]
----
[root@helper pv1]# exportfs -ra
[root@helper pv1]# 
----

Check.

[source,console]
----
[root@helper pv1]# exportfs 
/export       	<world>
/var/nfs/pv1  	<world>
/var/nfs/pv2  	<world>
/var/nfs/pv3  	<world>
[root@helper pv1]#
----

== open the firewall 

NFS v3 and v4 ports 

* 111/tcp 
* 2049/tcp 
* 20048/tcp 


[source,console]
----
[root@helper pv1]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp1s0
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 67/udp 53/tcp 53/udp 443/tcp 80/tcp 8080/tcp 6443/tcp 6443/udp 22623/tcp 22623/udp 9000/tcp 69/udp 111/tcp 2049/tcp 20048/tcp 50825/tcp 53248/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	
[root@helper pv1]# 
----

[source,console]
----
[nick@host2 ~]$ ping helper
PING helper.ocp4.example.com (192.168.7.77) 56(84) bytes of data.
64 bytes from api.ocp4.example.com (192.168.7.77): icmp_seq=1 ttl=64 time=0.189 ms
64 bytes from api.ocp4.example.com (192.168.7.77): icmp_seq=2 ttl=64 time=0.175 ms
^C
--- helper.ocp4.example.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 62ms
rtt min/avg/max/mdev = 0.175/0.182/0.189/0.007 ms
[nick@host2 ~]$ 
----

== check your work 

Mount an export. 

[source,console]
----
[nick@host2 ~]$ ls /mnt
[nick@host2 ~]$ 
----
Not that way!

[source,console]
----
[nick@host2 ~]$ mount helper:/var/nfs/pv1 /mnt
mount: only root can do that
[nick@host2 ~]$ 
----

This way.

[source,console]
----
[nick@host2 ~]$ sudo mount helper:/var/nfs/pv1 /mnt
[sudo] password for nick: 
[nick@host2 ~]$ 
----

Check.

[source,console]
----
[nick@host2 ~]$ df 
Filesystem            1K-blocks      Used Available Use% Mounted on
...
helper:/var/nfs/pv1    51089408   3995648  47093760   8% /mnt
[nick@host2 ~]$ 
----

Unmount. 

[source,console]
----
[nick@host2 ~]$ sudo umount /mnt
[nick@host2 ~]$ 
----

