= provide DNS with Bind 9 
Nick Hardiman <nhardima@redhat.com>
:source-highlighter: pygments
:toc:
:revdate: 11-01-2021


Install https://www.isc.org/bind/[ISC Bind].
Configure it to answer queries from the network. 
Tell Bind to 

* Answer questions about the _lab.example.com_ domain. Bind is authoritative for this domain, so it hands over records for hosts like guest1.lab.example.com. 
* Forward requests for _private.example.com_ records to dnsmasq.
* Forward all other questions to the home network's DNS server. 

This is a simple config that does not cover anything fancy like DNSSEC or split DNS. 


public network - 
  Gateway serves DHCP, DNS 

.guest1 network 
....
  |  
  | Internet
  |
+-+-------------------------------------+
|                                       |
|     ISP router                        |
|                                       |
+-+-------------------------------------+
  |
  | home network 
  | 192.168.1.0/24
  |
+-+-------------------------------------+
| enp1s0                                |
|    guest1.lab.example.com             |
| enp2s0                                |
+-+-------------------------------------+
  |
  | private network 
  | 192.168.152.0/24
  | privbr0

....


=== connect using SSH

[source,console]
....
[nick@host1 ~]$ ssh guest1
The authenticity of host 'guest1 (192.168.1.123)' can't be established.
ECDSA key fingerprint is SHA256:JcjI8AIHkUvat0qdM1OqDPzY0jughZC5ZOuU/uvApmk.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'guest1,192.168.1.123' (ECDSA) to the list of known hosts.
nick@guest1's password: 
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri May 29 12:15:41 2020
[nick@guest1 ~]$ 
....

When finished, disconnect with _exit_. 

[source,console]
----
[nick@guest1 ~]$ exit
logout
Connection to 192.168.152.218 closed.
[nick@host1 ~]$ 
----

== install bind 

[source,bash]
----
dnf install bind bind-utils 
----

before 

[source,bash]
----
[root@guest1 ~]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[root@guest1 ~]# 
----

enable and start 

[source,bash]
----
[root@guest1 ~]# systemctl enable named
Created symlink /etc/systemd/system/multi-user.target.wants/named.service → /usr/lib/systemd/system/named.service.
[root@guest1 ~]# 
[root@guest1 ~]# systemctl start named
[root@guest1 ~]# 
----

after 

[source,bash]
----
[root@guest1 named]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; vendor prese>
   Active: active (running) since Wed 2020-12-02 16:55:02 GMT; 3h 55min ago
  Process: 6703 ExecStart=/usr/sbin/named -u named -c ${NAMEDCONF} $OPTIONS (co>
  Process: 6700 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "y>
 Main PID: 6705 (named)
    Tasks: 5 (limit: 23328)
   Memory: 59.5M
   CGroup: /system.slice/named.service
           └─6705 /usr/sbin/named -u named -c /etc/named.conf

Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone 0.in-addr.arpa/IN: loaded >
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone 1.0.0.127.in-addr.arpa/IN:>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone localhost/IN: loaded seria>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone 1.0.0.0.0.0.0.0.0.0.0.0.0.>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: zone localhost.localdomain/IN: >
Dec 02 16:55:02 guest1.lab.example.com named[6705]: all zones loaded
Dec 02 16:55:02 guest1.lab.example.com named[6705]: running
Dec 02 16:55:02 guest1.lab.example.com systemd[1]: Started Berkeley Internet Name D>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: managed-keys-zone: Key 20326 fo>
Dec 02 16:55:02 guest1.lab.example.com named[6705]: resolver priming query complete
[root@guest1 named]# 
----

This text is displayed by a pager, which truncates long lines to fit the screen. 
Use arrow keys to scroll to the right and see the rest of the lines. 
To see all of these long lines without the pager, add some options to this command: `systemctl --no-pager --full status named`.



== forwarding 

before 

[source,bash]
----
[root@guest1 ~]# host www.google.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[root@guest1 ~]# 
----

[source,bash]
----
[root@guest1 ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
search home lab.example.com
nameserver 192.168.1.254
[root@guest1 ~]# 
----


== listen to all interfaces 

The machine has two network interfaces - _lo_ and _enp1s0_.

[source,bash]
----
[root@guest1 ~]# ip addr | grep 'inet '
    inet 127.0.0.1/8 scope host lo
    inet 192.168.1.217/24 brd 192.168.1.255 scope global dynamic noprefixroute enp1s0
[root@guest1 ~]# 
----

The DNS server is only listening to _lo_, the loopback interface. 
127.0.0.1 is the loopback interface's IPv4 address and [::1] is the IPv6 address. 

[source,bash]
----
[root@guest1 named]# ss -tl  '( dport = :domain or sport = :domain )'
State     Recv-Q    Send-Q       Local Address:Port         Peer Address:Port   
LISTEN    0         10               127.0.0.1:domain            0.0.0.0:*      
LISTEN    0         10                   [::1]:domain               [::]:*      
[root@guest1 named]# 
----

The config file contains https://bind9.readthedocs.io/en/latest/reference.html?highlight=listen-on#interfaces[listen-on] options.
These tell Bind to listen only to the loopback interface, so the rest of the network can't talk to it. 

[source,bash]
----
[root@guest1 ~]# grep listen-on /etc/named.conf 
  listen-on port 53 { 127.0.0.1; };
	listen-on-v6 port 53 { ::1; };
[root@guest1 ~]# 
----

Make Bind listen to the network address. 
This requires changing both the Bind config and firewalld's config. 

The IPv4 default is to listen to all interfaces. 
The IPv6 default is not to listen. 

Comment out the IPv4 line. 

[source,bash]
----
  #listen-on port 53 { 127.0.0.1; };
  listen-on-v6 port 53 { ::1; };
----

Check the change is OK. 
This is good. 

[source,bash]
----
[root@guest1 ~]# named-checkconf /etc/named.conf
[root@guest1 ~]# 
----

This is bad. The problem here is a typo: *~* instead of *#*. 

[source,bash]
----
[root@guest1 ~]# named-checkconf /etc/named.conf
/etc/named.conf:11: unknown option '~listen-on'
[root@guest1 ~]# 
----


Reload the configuration. 

[source,bash]
----
[root@guest1 ~]# systemctl reload named
[root@guest1 ~]# 
----

Bind starts listening to the IPv4 address 192.168.1.217.

[source,bash]
----
[root@guest1 ~]# ss -tln | grep :53
LISTEN    0         10           192.168.1.217:53               0.0.0.0:*       
LISTEN    0         10               127.0.0.1:53               0.0.0.0:*       
LISTEN    0         10                   [::1]:53                  [::]:*       
[root@guest1 ~]# 
----

Check. 

[source,bash]
----
[root@guest1 ~]# host www.google.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[root@guest1 ~]# 
----


== allow requests through the firewall 

Check DNS. 
Try a lookup from host _host1_. 

Nothing happens, then the attempt times out. 

[source,bash]
----
[nick@host1 ~]$ host www.google.com 192.168.1.217
...(big pause)...
;; connection timed out; no servers could be reached
[nick@host1 ~]$ 
----

Edit the firewall on guest1. 

[source,bash]
----
[root@guest1 ~]# firewall-cmd --add-service=dns
success
[root@guest1 ~]# firewall-cmd --add-service=dns --permanent
success
[root@guest1 ~]# 
----

Try again from host1. 
This time the reply is instant, but it's refused. 
Bind has a security feature that only allows queries from localhost. 
That's the next thing to change. 


[source,bash]
----
[nick@host1 ~]$ host www.google.com 192.168.1.217
Using domain server:
Name: 192.168.1.217
Address: 192.168.1.217#53
Aliases: 

Host www.google.com not found: 5(REFUSED)
[nick@host1 ~]$ 
----


== tell Bind to allow requests from the network 

Bind has many https://bind9.readthedocs.io/en/latest/reference.html?highlight=listen-on#access-control[access control] options, and most of them start with _allow-_.
The only one included in the default config file is _allow-query_. 

[source,bash]
----
[root@guest1 ~]# grep allow- /etc/named.conf 
	allow-query     { localhost; };
[root@guest1 ~]# 
----

the default is to allow all queries, so comment out the statement. 

[source,bash]
----
	#allow-query     { localhost; };
----

Reload the configuration with _systemctl reload named_.

Check again from host1. 


[source,bash]
----
[nick@host1 ~]$ host www.google.com 192.168.1.217
Using domain server:
Name: 192.168.1.217
Address: 192.168.1.217#53
Aliases: 

www.google.com has address 216.58.212.196
www.google.com has IPv6 address 2a00:1450:4009:80a::2004
[nick@host1 ~]$ 
----

Bind is now talking to the network. 
The next thing to do is give Bind a zone to manage. 



== add a zone file

A zone is a set of names and addresses for a name like www.lab.example.com. 
Add a zone file that describes lab.example.com. 

Bind already has some zones defined. 
The details are in files in the /var/named/ directory, such as named.ca which lists servers for the root domain. 
Bind's config has _zone_ options which tell Bind where these files are. 
One zone option is in /etc/named.conf and more are in /etc/named.rfc1912.zones
https://tools.ietf.org/html/rfc1912[RFC 1912] is about "Common DNS Operational and Configuration Errors" and says "certain zones should always be present", so this config file ticks that box. 


[source,bash]
----
[root@guest1 ~]# cd /var/named/
[root@guest1 named]# 
[root@guest1 named]# vi lab.example.com-records
----


These are the records. 
The file is spaced out to look more like a table (that's another suggestion from RFC 1912). 

[source,bash]
----
$TTL 3H
@    IN SOA    @ root.lab.example.com (
                    0    ; serial
                    1D    ; refresh
                    1H    ; retry
                    1W    ; expire
                    3H )    ; minimum
; these records are names and addresses for lab.example.com
             IN NS   dns1
             A       192.168.1.217
             AAAA    2a00:23c8:1d05:1e00:5054:ff:fe00:1
; these records are names and addresses for (HOST).lab.example.com
dns1         IN A    192.168.1.217
satellite1   IN A    192.168.1.214
satellite1.lab   IN A    192.168.1.214
guest1     IN A    192.168.1.217
----


[source,bash]
----
$TTL 3H
@    IN SOA    @ root.lab.example.com (
                    0    ; serial
                    1D    ; refresh
                    1H    ; retry
                    1W    ; expire
                    3H )    ; minimum
            IN NS   dns1.lab.example.com.
217         IN PTR dns1.lab.example.com.
214         IN PTR satellite1.lab.example.com.
214         IN PTR satellite1.lab.lab.example.com.
217         IN PTR guest1.lab.example.com.
----



[source,bash]
----
[root@guest1 named]# ls -la 
total 28
drwxrwx--T.  5 root  named  177 Dec  3 17:57 .
drwxr-xr-x. 21 root  root  4096 Dec  2 16:50 ..
-rw-r-----.  1 root  root   336 Dec  3 17:57 192.168.1-records
drwxrwx---.  2 named named   23 Dec  2 16:55 data
drwxrwx---.  2 named named   60 Dec  3 17:57 dynamic
-rw-r-----.  1 root  named 2253 Aug 21 11:12 named.ca
-rw-r-----.  1 root  named  152 Aug 21 11:12 named.empty
-rw-r-----.  1 root  named  152 Aug 21 11:12 named.localhost
-rw-r-----.  1 root  named  168 Aug 21 11:12 named.loopback
-rw-r-----.  1 root  root   527 Dec  3 17:55 lab.example.com-records
drwxrwx---.  2 named named    6 Aug 21 11:12 slaves
[root@guest1 named]# 
----

Change the group to match the other files. 
[source,bash]
----
[root@guest1 named]# chown .named lab.example.com-records 192.168.1-records 
[root@guest1 named]# 
----

No need to change the SELinux file type - all the files are _named_zone_t_.


=== more config 

Tell Bind where the new zone records are. 
Add these options to the bottom of /etc/named.conf.

[source,bash]
----
zone "lab.example.com" IN {
  type master;
  file "lab.example.com-records";
};

zone "1.168.192.in-addr.arpa" IN {
  type master;
  file "192.168.1-records";
};
----


Check the SOA records. 

[source,bash]
----
[root@guest1 named]# host -t SOA lab.example.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

lab.example.com has SOA record lab.example.com. root.lab.example.com.lab.example.com. 0 86400 3600 604800 10800
[root@guest1 named]# 
[root@guest1 named]# host -t SOA 1.168.192.in-addr.arpa localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

1.168.192.in-addr.arpa has SOA record 1.168.192.in-addr.arpa. root.lab.example.com.1.168.192.in-addr.arpa. 0 86400 3600 604800 10800
[root@guest1 named]#
----

Check the NS records. 

[source,bash]
----
[root@guest1 named]# host -t NS lab.example.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

lab.example.com name server dns1.lab.example.com.
[root@guest1 named]# 
[root@guest1 named]# host -t NS 1.168.192.in-addr.arpa localhost 
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

1.168.192.in-addr.arpa name server dns1.lab.example.com.
[root@guest1 named]# 
----

Check one of the A records and the matching PTR record. 


[source,bash]
----
[root@guest1 named]# host guest1.lab.example.com localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

guest1.lab.example.com has address 192.168.1.217
[root@guest1 named]# host 192.168.1.217 localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases: 

217.1.168.192.in-addr.arpa domain name pointer dns1.lab.example.com.
217.1.168.192.in-addr.arpa domain name pointer guest1.lab.example.com.
[root@guest1 named]# 
----

