= use RHSM (Red Hat Subscription Manager) to entitle a machine
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 05-01-2021

Use RHSM (Red Hat Subscription Manager) to https://access.redhat.com/solutions/253273[register and subscribe] your new machine.

A new machine's status is usually unknown. 

[source,console]
----
[root@host1 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Unknown

System Purpose Status: Unknown

[root@host1 ~]#
----


== register 

Add the machine to your account in the customer portal. 


[source,console]
----
subscription-manager register --username <username> --password <password> --auto-attach
----

The first time subscription-manager runs, it displays a warning about enabling a few plugins.

[source,console]
----
[nick@rhel8 ~]$ sudo subscription-manager register --username nick --password ';1!eB9-aW' --auto-attach
[sudo] password for nick: 
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: 12345678-2d45-41e7-a269-e71180cc5e5a
The registered system name is: rhel8.lab.example.com
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux for x86_64
Status:       Subscribed


WARNING

The yum/dnf plugins: /etc/dnf/plugins/subscription-manager.conf, /etc/dnf/plugins/product-id.conf were automatically enabled for the benefit of Red Hat Subscription Management. If not desired, use "subscription-manager config --rhsm.auto_enable_yum_plugins=0" to block this behavior.

[nick@rhel8 ~]$ 
----

Remove this registration with the command ``sudo subscription-manager unregister``.

=== check the portal 



== subscribe 

The machine is not yet entitled to updates. 
Use the _subscription-manager_ command to manage subscriptions for products.

=== find a suitable subscription 

With a developer subscription, there is only one. 

[source,console]
----
subscription-manager list --available 
----

=== attach your system to your subscription 

[source,console]
----
subscription-manager attach --pool=1234567890abcdef1234567890abcdef
----

=== check  

[source,console]
....
[root@host1 ~]# subscription-manager list
+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+
Product Name:   Red Hat Enterprise Linux for x86_64
Product ID:     479
Version:        8.3
Arch:           x86_64
Status:         Subscribed
Status Details: 
Starts:         15/03/17
Ends:           01/01/22

[root@host1 ~]# 
[root@host1 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Current

System Purpose Status: Not Specified

[root@host1 ~]# 
....



== check identity 

[source,bash]
----
[root@host1 ~]# subscription-manager identity
system identity: 12345678-d547-4e7b-8ca1-a6a03dfd692d
name: host1.lab.example.com
org name: 12345678
org ID: 12345678
[root@host1 ~]#
----



