= use RHSM (Red Hat Subscription Manager)
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 05-01-2021

Use RHSM (Red Hat Subscription Manager) to https://access.redhat.com/solutions/253273[register and subscribe] your new machine.

A new machine's status is usually unknown. 

[source,console]
----
[root@host1 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Unknown

System Purpose Status: Unknown

[root@host1 ~]#
----


== register 

Add the machine to your account in the customer portal. 

=== register 

Use the _subscription-manager_ command to manage subscriptions for products.

[source,console]
----
subscription-manager register --username <username> --password <password> --auto-attach
----

The first time subscription-manager runs, it displays a warning about enabling a few plugins.

[source,console]
----
[nick@rhel8 ~]$ sudo subscription-manager register --username nick --password ';1!eB9-aW' --auto-attach
[sudo] password for nick: 
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: faa0b03b-2d45-41e7-a269-e71180cc5e5a
The registered system name is: rhel8.lab.example.com
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux for x86_64
Status:       Subscribed


WARNING

The yum/dnf plugins: /etc/dnf/plugins/subscription-manager.conf, /etc/dnf/plugins/product-id.conf were automatically enabled for the benefit of Red Hat Subscription Management. If not desired, use "subscription-manager config --rhsm.auto_enable_yum_plugins=0" to block this behavior.

[nick@rhel8 ~]$ 
----

Remove this registration with the command ``sudo subscription-manager unregister``.

=== check the portal 



== subscribe 

The machine is not yet entitled to updates. 

=== find a suitable subscription 

With a developer subscription, there is only one. 

[source,console]
----
subscription-manager list --available 
----

=== attach your system to your subscription 

[source,console]
----
subscription-manager attach --pool=1234567890abcdef1234567890abcdef
----

=== check  

[source,console]
....
[root@host1 ~]# subscription-manager list
+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+
Product Name:   Red Hat Enterprise Linux for x86_64
Product ID:     479
Version:        8.3
Arch:           x86_64
Status:         Subscribed
Status Details: 
Starts:         15/03/17
Ends:           01/01/22

[root@host1 ~]# 
[root@host1 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Current

System Purpose Status: Not Specified

[root@host1 ~]# 
....


== set system purpose 

Subscription manager can set other values, like service level and usage.  
Setting these value helps with tasks like auto-attaching the right subscription from a list. 
Subscription-manager attempts to match fields in the available subscriptions. 

Subscription  manager tries to match fields in each subscription record. 

[source,console]
....
[root@host1 ~]# subscription-manager list --consumed
+-------------------------------------------+
   Consumed Subscriptions
+-------------------------------------------+
Subscription Name:   Employee SKU
...
Service Level:       Self-Support
Usage:               Development/Test
...
[root@host1 ~]# 
....

=== set service level 

Setting service level changes the line 'System Purpose Status: Not Specified' to 'System Purpose Status: Matched'.


No value is set. 

[source,console]
....
[root@host1 ~]# subscription-manager service-level --show
Service level preference not set
[root@host1 ~]#
....

List choices.

[source,console]
....
[root@host1 ~]# subscription-manager service-level --list
+-------------------------------------------+
           Available Service Levels
+-------------------------------------------+
Premium
Self-Support
Standard
[root@host1 ~]# 
....

Pick a value. 

This subscription is _Self-Support_.
If the wrong value is entered, remove the value with _subscription-manager service-level --unset_. 

[source,console]
....
[root@host1 ~]# subscription-manager service-level --set=Self-Support
service_level_agreement set to "Self-Support".
[root@host1 ~]# 
....

Check. 

[source,console]
....
[root@host1 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Current

System Purpose Status: Matched

[root@host1 ~]# 
....

=== set usage 

The usage field is similar. 

[source,console]
....
[root@host1 ~]# subscription-manager usage --list
+-------------------------------------------+
               Available usage
+-------------------------------------------+
 - Development/Test
 - Production
[root@host1 ~]# 
....

[source,console]
....
[root@host1 ~]# subscription-manager usage --set Development/Test
usage set to "Development/Test".
[root@host1 ~]# 
....

Setting this to something the machine is not entitled to shows a warning. 

[source,console]
....
[root@host1 ~]# subscription-manager usage --set Production
usage set to "Production".
[root@host1 ~]# 
....

[source,console]
....
[root@host1 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Current

System Purpose Status: Mismatched
- The requested usage preference "Production" is not provided by a currently consumed subscription.

[root@host1 ~]# 
....


== check identity 

[source,bash]
----
[root@host1 ~]# subscription-manager identity
system identity: 00f46344-d547-4e7b-8ca1-a6a03dfd692d
name: localhost.localdomain
org name: 11009103
org ID: 11009103
[root@host1 ~]#
----

[source,bash]
----
[root@localhost ~]# subscription-manager list 
+-------------------------------------------+
    Installed Product Status
+-------------------------------------------+
Product Name:   Red Hat Enterprise Linux for x86_64
Product ID:     479
Version:        8.2
Arch:           x86_64
Status:         Subscribed
Status Details: 
Starts:         15/03/17
Ends:           31/12/21

[root@localhost ~]# 
----


== disable and enable repositories  

A developer subscription adds 149 repos.
Types include source, debug and binary RPM.
Only these two are enabled. 

* rhel-8-for-x86_64-appstream-rpms
* rhel-8-for-x86_64-baseos-rpms

[source,bash]
----
[root@host1 ~]# subscription-manager repos --list-enabled
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-8-for-x86_64-appstream-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/appstream/os
Enabled:   1

Repo ID:   rhel-8-for-x86_64-baseos-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/baseos/os
Enabled:   1

[root@host1 ~]# 
----

=== disable all repos 

[source,bash]
----
subscription-manager repos --disable "*"
----

=== enable a few repos 

re-enable the two default repos. 

[source,bash]
----
subscription-manager repos --enable=rhel-8-for-x86_64-baseos-rpms 
subscription-manager repos --enable=rhel-8-for-x86_64-appstream-rpms 
----

Enable the Ansible repo as well. 

[source,bash]
----
subscription-manager repos --enable=ansible-2-for-rhel-8-x86_64-rpms 
----


=== check 

[source,bash]
----
[root@host1 ~]# subscription-manager repos --list-enabled
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-8-for-x86_64-appstream-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/appstream/os
Enabled:   1

Repo ID:   ansible-2-for-rhel-8-x86_64-rpms
Repo Name: Red Hat Ansible Engine 2 for RHEL 8 x86_64 (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2/os
Enabled:   1

Repo ID:   rhel-8-for-x86_64-baseos-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/baseos/os
Enabled:   1

[root@host1 ~]# 
----
