= create a server certificate
Nick Hardiman <nhardima@redhat.com>
:source-highlighter: highlight.js
:toc:
:revdate: 30-01-2021

Generate a certificate signed by the new CA. 
This example creates a replacement for the web server's self-signed certificate. 

Alternative approaches include using https://github.com/sgallagher/sscg[sscg] or https://letsencrypt.org/[Let's Encrypt].



== pick a name 

[source,shell]
....
[nick@guest1 ~]$ mkdir cert
[nick@guest1 ~]$ cd cert
[nick@guest1 cert]$ SERVER=www.lab.example.com
[nick@guest1 cert]$ 
....

== create a private key

Each server has its own key pair. 

Create the private key first. 

[source,shell]
....
[nick@guest1 cert]$ openssl genrsa -out $SERVER.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
................................................+++++
...+++++
e is 65537 (0x010001)
[nick@guest1 cert]$ 
....

View the file. 

This file is not encrypted, unlike the myca.key file.  

[source,shell]
....
[nick@guest1 cert]$ ls
www.lab.example.com.key
[nick@guest1 cert]$ 
[nick@guest1 cert]$ cat www.lab.example.com.key 
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAvJ/8MbRtlwwhw0hnYAfdApT1H/ZSbfWWjrwmLvKJzxR2E7HH
NyOsc/PnGxy7Flub+rfWXKnM7nBOt40vXWXetKDX8/lVCE2E3nq6tpK4s6EG+Gc7
t3V0KChvpU5Ar4sJ4EwZ5zqo4W38BbsSlDn2h7lVrw+DlnDp8iSKx0cN3VR+5bQi
...
9nTKgBSMolEAngGPBL1tfIGlak9aBkVy5ABp2rLBHmoAnNWExYjibG2noIZE13bZ
IViohwKBgCc+4d9AaYN5cwwiIzxHKl4EYigACh+PXjhmtwSMxISIzFOCy5hbgmmM
RS81/ON3Gns1SF/UDZgvKHC80T46nPOET+8pIhpIzGKkmaGJYje2Cv0RuUkiqv/L
gA+T7Vv27V0cK06En1TAljEr3g1U/0zBDEV4urTmSI2aVmWRf6Xp
-----END RSA PRIVATE KEY-----
[nick@guest1 cert]$ 
....




== create a CSR 

[source,shell]
....
openssl req -new   \
  -config ../CA/openssl.cnf     \
  -out $SERVER.csr   \
  -nodes  \
  -key $SERVER.key \
  -subj "/C=UK/ST=mystate/O=myorg/OU=myou/CN=$SERVER"
....

[source,shell]
....
[nick@guest1 cert]$ openssl req -new   \
>   -config ../CA/openssl.cnf     \
>   -out $SERVER.csr   \
>   -nodes  \
>   -key $SERVER.key \
>   -subj "/C=UK/ST=mystate/O=myorg/OU=myou/CN=$SERVER"
[nick@guest1 cert]$ 
....

view files 

[source,shell]
....
[nick@guest1 server]$ cat $SERVER.csr 
-----BEGIN CERTIFICATE REQUEST-----
MIICpjCCAY4CAQAwYTELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB215c3RhdGUxDjAM
BgNVBAoMBW15b3JnMQ0wCwYDVQQLDARteW91MSEwHwYDVQQDDBhteXNlcnZlci5s
YWIuZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDL
...
LgQsU3oKXI5dKx1AbR6OU6YiPq5fYMxm1+XxRXSmvEyvWOn01GL7KTKeX9B+nB9A
0vq9qcAaxc2mf5cXZEDkJ98SLxEx+IHT9nhXfz2e1eryfrL80NooTKoYK4wPo7sW
oRtOowJ/z7gPxA==
-----END CERTIFICATE REQUEST-----
[nick@guest1 server]$ 
....

Decode the CSR. 

[source,shell]
....
[nick@guest1 server]$ openssl req -in $SERVER.csr -text -noout
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = UK, ST = mystate, O = myorg, OU = myou, CN = myserver.lab.example.com
...
....



== send the CSR to the CA 

[source,shell]
....
[nick@guest1 cert]$ cp www.lab.example.com.csr ~/certauth/certreqs/
[nick@guest1 cert]$ 
....


== sign the CSR 

This part is done by the CA.

[source,shell]
....
cd ~/certauth/
SERVER=www.lab.example.com
openssl ca \
  -config openssl.cnf \
  -passin file:cakey.pass \
  -infiles certreqs/$SERVER.csr
....


[source,shell]
....
[nick@guest1 certauth]$ openssl ca \
>   -config openssl.cnf \
>   -passin file:cakey.pass \
>   -infiles certreqs/$SERVER.csr
Using configuration from openssl.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 2 (0x2)
        Validity
            Not Before: Feb  1 23:01:23 2021 GMT
            Not After : Feb  1 23:01:23 2022 GMT
        Subject:
            countryName               = UK
            stateOrProvinceName       = mystate
            organizationName          = myorg
            organizationalUnitName    = myou
            commonName                = www.lab.example.com
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Comment: 
                OpenSSL Generated Certificate
            X509v3 Subject Key Identifier: 
                AB:96:1A:06:43:19:49:76:C4:B2:26:6B:90:5A:1B:96:C3:C9:39:37
            X509v3 Authority Key Identifier: 
                keyid:92:75:37:21:03:E0:A5:D3:4D:B6:01:53:8F:A8:81:90:43:20:63:78

Certificate is to be certified until Feb  1 23:01:23 2022 GMT (365 days)
Sign the certificate? [y/n]:
....

The CA utility prompts before completing the job. 

[source,shell]
....
Sign the certificate? [y/n]:y


1 out of 1 certificate requests certified, commit? [y/n]y
Write out database with 1 new entries
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=UK, ST=mystate, O=myorg, OU=myou, CN=ca.lab.example.com
        Validity
            Not Before: Feb  1 23:01:23 2021 GMT
            Not After : Feb  1 23:01:23 2022 GMT
        Subject: C=UK, ST=mystate, O=myorg, OU=myou, CN=www.lab.example.com
...
4Y+Z7TRVxJOGMiX/XmC/+TpAFroJJ7J1L7rSl6Yo8Kb3
-----END CERTIFICATE-----
Data Base Updated
[nick@guest1 certauth]$ 
....


== check the signed certificate 

The signed certificate is displayed on the terminal and also written to the newcerts directory. 
The file name is a serial number. 


Two files 

[source,shell]
....
[nick@guest1 certauth]$ cat index.txt
V	220201174555Z		01	unknown	/C=UK/ST=mystate/O=myorg/OU=myou/CN=ca.lab.example.com
V	220201230123Z		02	unknown	/C=UK/ST=mystate/O=myorg/OU=myou/CN=www.lab.example.com
[nick@guest1 certauth]$ 
[nick@guest1 certauth]$ ls newcerts/
01.pem  02.pem
[nick@guest1 certauth]$ 
[nick@guest1 certauth]$ head newcerts/02.pem 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=UK, ST=mystate, O=myorg, OU=myou, CN=ca.lab.example.com
        Validity
            Not Before: Feb  1 23:01:23 2021 GMT
            Not After : Feb  1 23:01:23 2022 GMT
        Subject: C=UK, ST=mystate, O=myorg, OU=myou, CN=www.lab.example.com
[nick@guest1 certauth]$ 
....

== copy the file from the CA to the user

[source,shell]
....
[nick@guest1 certauth]$ cp newcerts/02.pem ~/cert/$SERVER.cer
[nick@guest1 certauth]$ 
[nick@guest1 certauth]$ ls -1 ~/cert/$SERVER*
/home/nick/cert/www.lab.example.com.cer
/home/nick/cert/www.lab.example.com.csr
/home/nick/cert/www.lab.example.com.key
[nick@guest1 certauth]$ 
....

The file contains the encoded certificate, along with all the decoded information. 
It's the same information shown by the command `openssl x509 -in www.lab.example.com.cer -text`.

