= install RHEL 8 (Red Hat Enterprise Linux version 8)
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 31-12-2020

Install RHEL 8 on your workstation for free. 


== install the OS

https://developers.redhat.com/articles/faqs-no-cost-red-hat-enterprise-linux/
one (1) physical system with up to eight processor sockets. 
an unlimited number of guest virtual machines (VMs).

These bullet points loosely based on 
https://developers.redhat.com/articles/getting-red-hat-developer-subscription-what-rhel-users-need-know/

* https://developers.redhat.com/products/rhel/download[Download Red Hat Enterprise Linux Server].
* https://developers.redhat.com/rhel8/install-rhel8/[Install on bare metal]. Remember to encrypt the disk.
* Attach your system to your subscription.
* Download updates from Red Hat.


== attach your system to your subscription 

Use RHSM (Red Hat Subscription Manager) to https://access.redhat.com/solutions/253273[register and subscribe] your new machine.

[source,console]
----
subscription-manager register --username <username> --password <password> --auto-attach
----

The first time subscription-manager runs, it displays a warning about enabling a few plugins.

[source,console]
----
[nick@rhel8 ~]$ sudo subscription-manager register --username nicktastic --password ';1!eB9-aW' --auto-attach
[sudo] password for nick: 
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: faa0b03b-2d45-41e7-a269-e71180cc5e5a
The registered system name is: rhel8.lab.example.com
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux for x86_64
Status:       Subscribed


WARNING

The yum/dnf plugins: /etc/dnf/plugins/subscription-manager.conf, /etc/dnf/plugins/product-id.conf were automatically enabled for the benefit of Red Hat Subscription Management. If not desired, use "subscription-manager config --rhsm.auto_enable_yum_plugins=0" to block this behavior.

[nick@rhel8 ~]$ 
----

Remove this registration with the command ``sudo subscription-manager unregister``.





== check out the desktop

If you've used Fedora as a workstation but only used RHEL on the command line, 
you may not have a clue what RHEL's desktop looks like. 
Think Fedora from a couple years ago (Fedora 28, to be exact).
Fedora gets the latest and greatest updates.
RHEL provides a stable platform.






== next steps 

If you're looking for things to play with, have a look at cockpit and Insights. 

When you SSH to your fresh install, you see this MOTD (Message Of The Day).
If you're on the Gnome desktop, you can only see these messages by looking at their files - ``cat /etc/motd.d/*``.

[source,console]
----
somehost:~ nick$ ssh 10.0.1.4
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Thu May 14 17:29:53 2020 from 10.0.1.3
[nick@rhel8 ~]$ 
----


