
= libvirt storage volume 
Nick Hardiman 
:source-highlighter: pygments
:toc: 

Start with a basic image, make a few changes.

.storage pool containing two volumes
[a2s,libvirt-storage-volume]
....
.-------------------------------------.
|                                     |    
|   my_images                         |    
|                                     |    
|   +-----------------------------+   |    
|   |                             |   |   
|   |  rhel-8.2-x86_64-kvm.qcow2  |   |
|   |                             |   |  
|   +-----------------------------+   |  
|                                     |    
|   +-----------------------------+   |    
|   |                             |   |   
|   |  guest1.qcow2               |   |
|   |                             |   |  
|   +-----------------------------+   |  
.-------------------------------------. 
....

== prereqs 

* laptop with 500GB storage and 32GB memory 
* Fresh RHEL 8 install 
* developer subscription 
* storage pool, my_images
 

== install 

Edit disk image with qemu-img. 
View VM's desktop with virt-viewer?
Add a bridge with brctl? or bridge? or nmcli?
virt-resize from libguestfs-tools


Install libvirt client tools.

The virt module provides most of the tools. 
Couple more from the appstream repository, virt-viewer, cockpit-machines 

[source,console]
----
[nick@host ~]$ sudo dnf module list virt 
Updating Subscription Management repositories.
Last metadata expiration check: 0:16:21 ago on Thu 14 May 2020 17:14:06 BST.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Name         Stream              Profiles           Summary                     
virt         rhel [d][e]         common [d]         Virtualization module       

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled
[nick@host ~]$ 
----

```
sudo dnf module install virt
sudo dnf install libguestfs-tools
sudo dnf install virt-install
```


== RHEL 8 KVM image

Red Hat provide a disk image that's ready to use.  
It's a minimal install, with no graphical desktop. 

This is a qcow2 (QEMU v2) disk image. 
There are many other volume formats, from bochs to vpc. 
The image is split into three parts.

* The first part is tiny and contains the BIOS
* The second part is the /boot partition.
* The third part is another partition. LVM splits this into three volumes - root file system, home directory, and swap space.


== download the RHEL 8 KVM image  

The https://access.redhat.com/downloads/content/479/ver=/rhel---8/8.2/x86_64/product-software[download page for RHEL 8]

This page also contains a tiny boot ISO and a big install DVD. 
For more information, check out the https://access.redhat.com/solutions/104063[Understanding the various RHEL .iso files] page. 

Download this KVM image and copy to the ``guest_images`` directory. 

[source,console]
----
[nick@host ~]$ virt-filesystems -lh -a guest-images/rhel-8.2-x86_64-kvm.qcow2 
Name       Type        VFS   Label  Size  Parent
/dev/sda2  filesystem  vfat  -      100M  -
/dev/sda3  filesystem  xfs   root   9.9G  -
[nick@host ~]$ 
----

This image has no root password set. 
It does have cloud-init enabled for public cloud systems. 


== create the guest1 KVM image  

Don't use the original image file for creating a machine. 
It can remain as the backup file. 
Make a copy and edit that instead.

Create an empty qcow2 image file. 
The command _virsh vol-create-as_ needs a pool name, the new file name and how big  the volume should be. If you can't remember your pool name, run _virsh pool-list_ to check.

[source,console]
----
[nick@host ~]$ virsh vol-create-as my_images guest1.qcow2 20G
Vol guest1.qcow2 created

[nick@host ~]$ 
----

Check the empty volume. Have a look inside the directory. 

[source,console]
----
[nick@host ~]$ ls -lh guest-images/
total 22G
-rw-------. 1 nick nick  20G May 15 15:51 guest1.qcow2
-rw-r--r--. 1 nick nick 1.1G May 15 15:48 rhel-8.2-x86_64-kvm.qcow2
[nick@host ~]$ 
----

If you want to remove this new file and start again, you can delete it with _virsh vol-delete_. This command also removes the details libvirt keeps about the storage volume. 
[source,console]
----
[nick@host1 ~]# virsh vol-delete guest1.qcow2 my_images
Vol guest1.qcow2 deleted

[nick@host1 ~]#
----


Fill up the new volume using the _virt_resize_ command. 
This doesn't actually resize one file in-place - it reads one file and overwrites a second file. 
Virt_resize expands the volume in the second file while it's copying.

Libvirt does come with a volume copying command, _virsh vol-clone_. It can make a new copy, but it can't change its size. 

[source,console]
----
[nick@host ~]$ virt-resize --expand /dev/sda3 guest-images/rhel-8.2-x86_64-kvm.qcow2 guest-images/guest1.qcow2 
[   0.0] Examining guest-images/rhel-8.2-x86_64-kvm.qcow2
**********

Summary of changes:

/dev/sda1: This partition will be left alone.

/dev/sda2: This partition will be left alone.

/dev/sda3: This partition will be resized from 9.9G to 19.9G.  The 
filesystem xfs on /dev/sda3 will be expanded using the ‘xfs_growfs’ 
method.

**********
[   3.8] Setting up initial partition table on guest-images/guest1.qcow2
[  15.0] Copying /dev/sda1
[  15.0] Copying /dev/sda2
[  15.1] Copying /dev/sda3
 100% ⟦▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒⟧ 00:00
[  31.2] Expanding /dev/sda3 using the ‘xfs_growfs’ method

Resize operation completed with no errors.  Before deleting the old disk, 
carefully check that the resized disk boots and works correctly.
[nick@host ~]$ 
----

== customize the guest1 KVM image  

This image has no root password and no other accounts, so we can't log in.
Change this and a few other things with the ``virt-customize`` command.

[source,console]
----
virt-customize \
  --add  guest-images/guest1.qcow2  \
  --root-password  password:'x%5ckA-1'  \
  --hostname  guest1.lab.example.com  \
  --timezone  'Europe/London'  \
  --selinux-relabel
----

The command takes a few seconds. ``virt-customize``` prints an activity log, along with seconds elapsed.

[source,console]
----
[nick@host ~]$ virt-customize --add guest-images/guest1.qcow2 --root-password password:'x%5ckA-1' --hostname guest1.lab.example.com
[   0.0] Examining the guest ...
[   4.6] Setting a random seed
[   4.6] Setting the machine ID in /etc/machine-id
[   4.6] Setting the hostname: guest1.lab.example.com
[   4.6] Setting the timezone: Europe/London
[   4.7] Setting passwords
[   5.9] SELinux relabelling
[  18.3] Finishing off
[nick@host ~]$ 
----



== advanced tricks

Create your own qcow2 image using image builder. 


