= check KVM, QEMU and libvirt 
Nick Hardiman 
:source-highlighter: pygments
:toc: 
:revdate: 05-01-2021


One big physical machine can run many small virtual machines. 
KVM, QEMU and libvirt make virtualization work. 
Many virtualization packages are already installed. 

https://www.linux-kvm.org/page/Main_Page[Linux KVM] is the engine that makes virtualization work on RHEL 8. 

https://www.qemu.org/[QEMU] is a machine emulator. 
QEMU handles hardware emulation for virtual machines.

The https://libvirt.org/[libvirt] project provides a virtualization management system. 
It's used by RHV (Red Hat Virtualization), Openstack, and even the latest Openshift.



== KVM 

The  https://www.redhat.com/en/topics/virtualization/what-is-KVM hypervisor[KVM (Kernel-based Virtual Machine) hypervisor] is built into Linux. 
Run ``lsmod | grep kvm`` to see the kernel modules.

== QEMU 

[source,console]
----
/usr/libexec/qemu-kvm --version
----

[source,console]
----
yum info qemu-kvm
----


== libvirt 

libvirt provides a management interface to QEMU. 
Libvirt is used by the https://www.redhat.com/en/technologies/virtualization/enterprise-virtualization[RHV (Red Hat Virtualization)] system, and RHV's upstream open-source project https://www.ovirt.org/[oVirt].


libvirt-daemon manages the virtualization. 
The version is a https://libvirt.org/news.html[couple years old]. 
This libvirt version was included in Fedora 28, which was used as the base of RHEL 8. 

[source,console]
----
[nick@host ~]$ /usr/sbin/libvirtd --version
/usr/sbin/libvirtd (libvirt) 4.5.0
[nick@host ~]$ 
----

systemd service libvirtd is running. 
This created a couple network devices - 
a bridge devices named virbr0 
a https://en.wikipedia.org/wiki/TUN/TAP[TUN/TAP] network interface named virbr0-nic, 
used by the bridge. 
Run ``nmcli device status`` to see theses. 







The https://libvirt.org/[libvirt] project provides a virtualization management system. 
It's used by RHV (Red Hat Virtualization), Openstack, and even the latest Openshift.



== virtualization components that are already installed  

Many qemu and libvirt-daemon packages are already installed. 
The  https://www.redhat.com/en/topics/virtualization/what-is-KVM hypervisor[KVM (Kernel-based Virtual Machine) hypervisor] is built into Linux. 
Run ``lsmod | grep kvm`` to see the kernel modules.

QEMU handles hardware emulation for virtual machines.
libvirt provides a management interface to QEMU. 
Libvirt is used by the https://www.redhat.com/en/technologies/virtualization/enterprise-virtualization[RHV (Red Hat Virtualization)] system, and RHV's upstream open-source project https://www.ovirt.org/[oVirt].


libvirt-daemon manages the virtualization. 
The version is a https://libvirt.org/news.html[couple years old]. 
This libvirt version was included in Fedora 28, which was used as the base of RHEL 8. 

[source,console]
----
[nick@host ~]$ /usr/sbin/libvirtd --version
/usr/sbin/libvirtd (libvirt) 4.5.0
[nick@host ~]$ 
----

systemd service libvirtd is running. 
This created a couple network devices - 
a bridge devices named virbr0 
a https://en.wikipedia.org/wiki/TUN/TAP[TUN/TAP] network interface named virbr0-nic, 
used by the bridge. 
Run ``nmcli device status`` to see theses. 
