= check out the kernel
Nick Hardiman 
:source-highlighter: pygments
:toc: 
:revdate: 08-01-2021



== kernel version 

Actually, the version isn't very informative. 
The release is. 

[source,console]
----
[root@host1 ~]# uname --kernel-version
#1 SMP Wed Dec 16 03:30:52 EST 2020
[root@host1 ~]# man uname 
[root@host1 ~]# 
[root@host1 ~]# uname --kernel-release
4.18.0-240.10.1.el8_3.x86_64
[root@host1 ~]# 
----

The *4.18* part of that release, the major and minor numbers at the beginning of the line, correspond to the upstream kernel. 
The upstream 4.18 kernel is described in mind-bending detail at https://kernelnewbies.org/Linux_4.18[Kernelnewbies].

The 4.18 release is not the https://www.kernel.org/[latest release] - Fedora regularly updates kernel versions, but RHEL doesn't.
The RHEL 8 kernel is kept as stable, secure and bug-free as possible, so those numbers won't change much over the lifetime of RHEL 8. 
For more information, see the article 
https://www.redhat.com/en/blog/what-latest-kernel-release-my-version-red-hat-enterprise-linux[What is the latest kernel release for my version of Red Hat Enterprise Linux?
].

The *el8_3* part shows the upstream kernel code was copied for RHEL and worked on for the 8.3 release. 


== kernel file 

[source,console]
----
[root@host1 ~]# grep CMDLINE /etc/default/grub 
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet"
[root@host1 ~]# 
----


== kernel packages 

[source,console]
----
[root@host1 ~]# dnf list kernel
Updating Subscription Management repositories.
Last metadata expiration check: 1:59:14 ago on Fri 08 Jan 2021 10:37:36 GMT.
Installed Packages
kernel.x86_64                                  4.18.0-240.el8                                         @anaconda                     
kernel.x86_64                                  4.18.0-240.10.1.el8_3                                  @rhel-8-for-x86_64-baseos-rpms
[root@host1 ~]# 
----


== kernel command line 

command line does contain quiet. 

Grub menu line is defined here. 

[source,console]
----
[root@host1 ~]# grep CMDLINE /etc/default/grub 
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet"
[root@host1 ~]# 
----


What was used is here. 
The second half of this line matches the line in /etc/default/grub. 

[source,console]
----
[root@host1 boot]# cat /proc/cmdline 
BOOT_IMAGE=(hd0,msdos2)/vmlinuz-4.18.0-240.10.1.el8_3.x86_64 root=/dev/mapper/rhel-root ro crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet
[root@host1 boot]# 
----


== kernel log 

The kernel keeps its own activity log. 
This is partly because it has to keep track of its activity when the system starts, before all the regular logging things are available.
Log messages are kept in a https://en.wikipedia.org/wiki/Circular_buffer[circular buffer] im memory. 
The manual pages call this the log buffer or ring buffer. 

While the system is running, kernel messages also appear in _/var/log/messages_. 
There is no separate _/var/log/kern.log_. 

Important messages are copied to the console. 
In the olden days, when computers had consoles and operators hanging around to see the messages, this made sense. 
These days, a server machine has no screen, let alone someone looking at it. 

View the kernel log with journalctl. 

[source,console]
----
[root@host1 boot]# journalctl --dmesg 
-- Logs begin at Thu 2021-01-07 09:58:25 GMT, end at Thu 2021-01-07 16:22:56 GMT. --
Jan 07 09:58:25 host1.silvan.uk kernel: Linux version 4.18.0-240.10.1.el8_3.x86_64 (mockbuild@x86-vm-08.build.eng.bos.redhat.com) (>
Jan 07 09:58:25 host1.silvan.uk kernel: Command line: BOOT_IMAGE=(hd0,msdos2)/vmlinuz-4.18.0-240.10.1.el8_3.x86_64 root=/dev/mapper>
Jan 07 09:58:25 host1.silvan.uk kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
...
----


