= use ansible lint 
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 04-06-2020

Use ansible-lint, a checker.

This utility is not included in the ansible package.


== install 

Install using pip. 
The ansible-lint tool isn't available in a Red Hat repo, so you can't use _dnf_. 

[source,shell]
----
python -m venv ansible-venv
source ansible-venv/bin/activate
pip install --upgrade pip setuptools
----

Don't install using platform-python. 
In this case, you can get away with installing ansible-lint without doing damage to system python, by running the command ``sudo /usr/libexec/platform-python3.6 -m pip install ansible-lint``. But it's a bad habit. 



[source,shell]
----
(ansible-venv) [nick@guest1 ~]$ pip install ansible-lint
Collecting ansible-lint
  Using cached ansible_lint-4.2.0-py2.py3-none-any.whl (57 kB)
Collecting six
...
Successfully installed MarkupSafe-1.1.1 ansible-2.9.9 ansible-lint-4.2.0 cffi-1.14.0 cryptography-2.9.2 jinja2-2.11.2 pycparser-2.20 pyyaml-5.3.1 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 six-1.15.0
(ansible-venv) [nick@guest1 ~]$ 
----



== use 

Run ``ansible-lint``. With no options, it checks everything in the current directory.

Several complaints are displayed. 

[source,shell]
----
[nick@guest1 ~]$ cd ansible
[nick@guest1 ansible]$ 
[nick@guest1 ansible]$ ansible-lint 
[201] Trailing whitespace
ansible-target.yml:2
- name: ansible-target test 
...
[703] Should change default metadata: author
roles/ansible-target/meta/main.yml:1
{'meta/main.yml': {'galaxy_info': {'author': 'your name', 'description': 'your role description', 'company': 'your company (optional)', 'license': 'license (GPL-2.0-or-later, MIT, etc)', 'min_ansible_version': 2.9, 'galaxy_tags': [], '__line__': 1, '__file__': '/home/nick/ansible/roles/ansible-target/meta/main.yml'}, 'dependencies': [], '__line__': 1, '__file__': '/home/nick/ansible/roles/ansible-target/meta/main.yml', 'skipped_rules': []}}
...
----

The many messages are in two groups.  

* trailing whitespace, in files ansible-target.yml and roles/ansible-target/tasks/main.yml.
* default metadata, in roles/ansible-target/meta/main.yml

Rule number 201, the one that produced the 'trailing whitespace' complaint, is tagged as _formatting__.

[source,shell]
----
[nick@guest1 ansible]$ ansible-lint -T | grep 201
ANSIBLE0002 ['[201]']
formatting ['[204]', '[203]', '[202]', '[205]', '[201]', '[104]', '[206]']
[nick@guest1 ansible]$ 
----

Ignore rule 201
----
ansible-lint -x 201
----
Ignore all formatting checks. 
----
ansible-lint -x formatting
----


=== rule files 

Location of rule files is displayed in the help.

[source,shell]
----
(ansible-venv) [nick@guest1 ~]$ ansible-lint  -h
...
  -R                    Use default rules in /home/nick/ansible-
                        venv/lib64/python3.8/site-packages/ansiblelint/rules
...
----

The code for rule _[201] Trailing whitespace_ is in file ``site-packages/ansiblelint/rules/TrailingWhitespaceRule.py``.



== fix errors 

Most of these files were created by the ``ansible-galaxy`` command.
ansible-lint is complaining about the meta/main.yml. 
It wasn't touched because it isn't required yet, so ansible-lint does not like the default layout. 
The file can be edited or deleted - either is fine. 

[source]
....
ansible-target/
├── defaults
│   └── main.yml <-- edited
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── README.md
├── tasks
│   └── main.yml <-- edited
├── templates
│   └── sudoers <-- added
├── tests
│   ├── inventory
│   └── test.yml
└── vars
    └── main.yml
....

Clean up and try again. 

....
rm roles/ansible-target/meta/main.yml 
rmdir roles/ansible-target/meta/
ansible-lint
....

== commit fixes 

Keep on top of SCM (Source Code Management).
Commit your code and post it to the central repo.

[source]
----
git status
git commit -am 'ansible-lint'
git push
----
