= create a shared git repo
Nick Hardiman
:source-highlighter: highlight.js
:revdate: 02-06-2020

Create a common repository for code collaboration.

Add two git repositories on guest1.

* a repo named *content1.git*. No, the name doesn't make sense. This is the common copy for sharing, located on guest1.
* a clone named *content1*. This is the development copy to hack. This copy is on guest1 too, but it could be anywhere in the network.

.git repos 
....
.-----------------------------------------.  
|                                         |
|  git repositories on guest1             |
|                                         |
|   +--------------+    +--------------+  |
|   |              |    |              |  |
|   | content1     |    | content1.git |  |
|   | (clone)      |--->| (remote)     |  |
|   |              |    |              |  |
|   +--------------+    +--------------+  |
.-----------------------------------------.  
....


Every new piece of code needs a new home. 

This article spells out the git commands for visitors from the version control worlds of Perforce, Mercurial, ClearCase and elsewhere. 

== an SCM (Source Code Manager)

We're going to develop code in the directory /home/nick/content1/. 
We need a way of keeping this content safe and sharing it. 
Create a git repository called _content1.git_ to manage this code.
This will become the new remote for all clones. 

There is plenty that isn't done here. 

* No workflow - no branching, tests, submodules, and certainly no CI pipelines.  
* No private group access, or general public access - this instance of git can be used across the network, but is not shared with others. That takes config and permission work. 

This is an instance of core git, included in RHEL 8's appstream repo. Git tools are a central component of much fancier products like https://gitea.io/[Gitea], https://gogs.io/[Gogs],	https://about.gitlab.com/install/?version=ce[GitLab CE], and https://rhodecode.com/open-source[RhodeCode CE]. This git doesn't run any extra processes because it doesn't run as a daemon. Instead, the SSH service handles the transport and running git commands.  


== git on the network 

The new repo lives on a new host named _git1.lab.example.com_. This new _git1_ host  can be accessed across the network using the SSH protocol. The _git1_ host may look like a new network location, but isn't actually a new machine - it's another name for guest1. 


=== which network transport 

There are a few ways to set up authentication and file transfer. 
We could use NFS, web, SSH or git's own protocol, also called git. 
Which access protocol is the easiest to set up?

We want multiple locations to access git over the network. This git service will be accessed from other guest machines. That means setting up a service to handle network transport. There are a few choices -  which is best? 
(spoiler - it's SSH)

* simple file-based repository with NFS. A file-based repo is a local solution, not a network solution. Install NFS to share the same files among many machines. Allow NFS traffic on firewalls.
* dumb HTTP service. Install Apache, then set up read-only HTTP access for reading. Doesn't handle writing - that requires another service. Allow web traffic on firewalls.
* smart HTTP service. Install Apache, then configure a new site with WEbDAV read/write access. Open firewalls.
* git. Practically no work to do, and practically no security either - allow the world to read and write everything. Make sure git's in a trusted place and open git port 9418 on firewalls.
* SSH. There's no install work to do because it's already running. And no security work either, because SSH handles access control and traffic encryption. SSH port 22 is already open on firewalls. 



== add DNS for git

Help host1 users find the common git repo. 
Add a new host name *git1* and fully qualified name *git1.lab.example.com* to DNS. 

DNS is controlled by dnsmasq running on the host machine. 
We can't add a line to dnsmasq's config (/var/lib/libvirt/dnsmasq/default.conf) because libvirt will overwrite the file and our change will be lost.
We can add more libvirt config, to its XML files.  
But it's simpler to a line to /etc/hosts. 
Libvirt reads this file when it starts. 

This is the only change made on the host machine. 

[source,shell]
....
[nick@host1 ~]$ sudo bash -c 'echo "192.168.122.4 git git.lab.example.com" >> /etc/hosts'
[sudo] password for nick: 
[nick@host1 ~]$ 
[nick@host1 ~]# sudo systemctl restart libvirtd
[nick@host1 ~]# 
....

Check.

[source,shell]
....
[nick@host1 ~]# host git1.lab.example.com 192.168.122.1
Using domain server:
Name: 192.168.122.1
Address: 192.168.122.1#53
Aliases: 

git1.lab.example.com has address 192.168.122.4
[nick@host1 ~]# 
....


== install  

Back to guest1.

Install git with the command ``sudo dnf install git``.
This installs the _git-core_ package and many perl modules. 



== configure a few things

Create a common group. 
Add a few users to this group.
These tasks are only done once. 

There are plenty of commands that need elevated privileges here. 
Rather than typing _sudo_ every time, use the root account. 


Create a common directory. 

[source,shell]
....
[nick@guest1 ~]$ sudo su -
[root@guest1 ~]# groupadd scm
[root@guest1 ~]# usermod -a -G scm nick
[root@guest1 ~]# 
[root@guest1 ~]# mkdir /var/git
....

Change the group ownership.

[source,shell]
....
[root@guest1 ~]# chown root.scm /var/git/
[root@guest1 ~]# 
[root@guest1 ~]# exit
logout
[nick@guest1 ~]$ 
....

Add git user configuration. 

Configure git. 
Otherwise, committing the file fails with a 'fatal: empty ident name not allowed' error. 

[source,shell]
....
[nick@guest1 ~]$ git config --global user.email "nick@lab.example.com"
[nick@guest1 ~]$ git config --global user.name "Nick Hardiman"
[nick@guest1 ~]$ 
[nick@guest1 ~]$ cat .gitconfig 
[user]
	email = nick@lab.example.com
	name = Nick Hardiman
[nick@guest1 ~]$ 
....


== create a common repository 

Create a common git repo to share with the group. 

These tasks are repeated for every new git repo. 

[source,shell]
....
[nick@guest1 ~]$ sudo su -
[root@guest1 ~]#  cd /var/git/
[root@guest1 git]# NEW_REPO=content1.git
[root@guest1 git]# git init --bare --shared=group $NEW_REPO
Initialized empty shared Git repository in /var/git/content1.git/
[root@guest1 git]# 
[root@guest1 git]# chgrp -R scm $NEW_REPO
[root@guest1 git]# 
[root@guest1 git]# exit
logout
[nick@guest1 ~]$ 
....


== create a personal repository 

Clone the new shared repo for your personal use. 
Copy the repo to your home directory with git clone. 

This command uses SSH to connect to the git host. Some SSH security messages appear. 

[source,shell]
....
[nick@guest1 ~]$ git clone git1:/var/git/content1.git
Cloning into 'content1'...
The authenticity of host 'git1 (192.168.122.4)' can't be established.
ECDSA key fingerprint is SHA256:nTrTxkZuJVURnVOqoC563D7F4yd3fnWOMewJBeL7bXw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1,192.168.122.4' (ECDSA) to the list of known hosts.
....

A warning appears about the suspiciously empty directory. 

[source,shell]
....
warning: You appear to have cloned an empty repository.
[nick@guest1 ~]$ 
[nick@guest1 ~]$ ls -a content1/
.  ..  .git
[nick@guest1 ~]$ 
....


== create content 

Create a bash script on guest1.
The script is created by a one-liner command, which requires some tricky quoting and the special character \n.

[source,shell]
....
[nick@guest1 ~]$ cd content1/
[nick@guest1 content1]$ echo -e '#!'"/bin/bash\necho 'hello world'\n" > hello-world.sh
[nick@guest1 content1]$ chmod 754 ./hello-world.sh 
....

Does it work? 

[source,shell]
....
[nick@guest1 content1]$ ./hello-world.sh 
hello world
[nick@guest1 content1]$ 
....

Time to store a copy somewhere safe. 



== commit to both repositories 

Commit the new file to your personal repo. 

[source,shell]
....
[nick@guest1 content1]$ git add hello-world.sh 
[nick@guest1 content1]$ git commit -m 'create hello-world.sh'
[master (root-commit) 540c540] create hello-world.sh
 1 file changed, 3 insertions(+)
 create mode 100755 hello-world.sh
[nick@guest1 content1]$ 
....

Copy to the shared repo.

[source,shell]
....
[nick@guest1 content1]$ git push 
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 262 bytes | 262.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git1:/var/git/content1.git
 * [new branch]      master -> master
[nick@guest1 content1]$
....




== set up key-based login 

We have to type in our account password every time the remote repository is accessed. 

!!! no it doesnt

That gets tiresome. 
Git provides credential helpers for web access, but not for SSH. 
Set up public key access so SSH won't prompt for a password. 

Append your public key to the list of authorized keys. 

[source,shell]
----
[nick@guest1 content1]$ cd
[nick@guest1 ~]$ cat .ssh/id_rsa.pub  >> .ssh/authorized_keys 
[nick@guest1 ~]$ 
----

Check.

[source,shell]
----
[nick@guest1 content1]$ ssh git1.lab.example.com
The authenticity of host 'git1.lab.example.com (192.168.122.4)' can't be established.
ECDSA key fingerprint is SHA256:nTrTxkZuJVURnVOqoC563D7F4yd3fnWOMewJBeL7bXw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1.lab.example.com' (ECDSA) to the list of known hosts.
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Jul  3 12:58:51 2020 from 192.168.122.1
[nick@guest1 ~]$ 
[nick@guest1 ~]$ logout
Connection to git1.lab.example.com closed.
[nick@guest1 content1]$ 
----



== test with another user 

!!! someuser doesnt exist in these docs. 

Use someuser. 
Must be in scm group. 

[source,shell]
----
[nick@guest1 ~]$ sudo su - someuser
[someuser@guest1 ~]$ 
----

Copy the repo. 
Check git clone works.


[source,shell]
----
[someuser@guest1 ~]$ git clone git1:/var/git/content1.git
Cloning into 'content1'...
The authenticity of host 'git1 (192.168.122.4)' can't be established.
ECDSA key fingerprint is SHA256:nTrTxkZuJVURnVOqoC563D7F4yd3fnWOMewJBeL7bXw.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'git1,192.168.122.4' (ECDSA) to the list of known hosts.
someuser@git1's password: 
Cloning into 'content1'...
someuser@git1's password: 
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (12/12), done.
[someuser@guest1 ~]$ 
----

Have any files appeared?

[source,shell]
----
[someuser@guest1 ~]$ ls content1/
hello-world.sh
[someuser@guest1 ~]$  
----

Check git push.

Add to the repo. 
Use these commands to configure git and add a new file.

[source,shell]
----
git config --global user.email "someuser@lab.example.com"
git config --global user.name "Some User"
cd content1
touch someuser-test 
git add someuser-test
git commit -m'create someuser-test'
git push
----

Done. 

[source,shell]
----
[someuser@guest1 ~]$ logout
[nick@guest1 ~]$ 
----

