= hardware  
Nick Hardiman 
:source-highlighter: pygments
:toc:
:revdate: 24-10-2020

A computer system is built up of layers. There's the hardware layer at the bottom, then a layer of software that makes this hardware work, then another layer of software that makes a computer useful. The software in the middle, being halfway between hardware and software, is called firmware. 

The Raspberry Pi is packed with hardware. "Hardware" in computer terms covers pretty much everything you can see, including the PCB (Printed Circuit Board), ICs (Integrated Circuits) in the middle and connectors around the edges. 
Each piece of hardware is an engineering marvel, from the copper foil tracks to the surface-mount resistors. 
Comparing a Raspberry Pi to a server board may feel like comparing a rock to a rail gun, but that misses the nerdy engineering beauty hidden in the small details. 


== chips 

If you're wondering where the ARM CPU is, take a look at the light silver square - the one with a few other lines of text starting with "BROADCOM®" printed on top. 
That covers the Broadcom BCM2711 SoC (System on Chip), which is packed with ARM cores, device controllers, GPU (Graphics Processor and other silicon machines.

See the black chip with https://www.via-labs.com/product_show.php?id=48[VIA VL805] written on it?
That bridges the gap between the the PCI Express device on the SoC and the USB connectors. 

More chips 

* https://www.maxlinear.com/product/power-management/universal-pmics/universal-pmics/mxl7704[MXL7704] - PMIC [Power Management Integrated Circuit]  
* https://www.dialog-semiconductor.com/products/power-management/pmics/da9121[da9121]  - another PMIC 
* https://www.broadcom.com/products/ethernet-connectivity/phy-and-poe/copper/gigabit/bcm54213pe[BCM54213PE] - ethernet
* OAA47 D9ZCL - 8GB memory 
* https://www.cypress.com/documentation/product-overviews/cyw43455-wiced-ieee-80211ac-wifi-bluetooth-41-connectivity-solution[Cypress CYW43455] - Wifi and bluetooth. This is hidden under the shiny silver RF shield. 



== buy hardware 

Buying computer hardware is expensive, even at this home-hobbyist level. In fact, the first barrier to getting started with a Raspberry Pi 4 is the cash barrier. Working with the US dollar, de-facto currency of the world, expect to lay out a few hundred bucks. 

You need an RPi4 - yep, so far so obvious - and you also need a fair amount of other hardware. 

* *current network*. Perhaps this is your home lab.
* *ethernet cable*. This connects the current network to the Raspberry Pi
* *Raspberry Pi 4 model B 8GB*. Don't get the 1, 2 or 4GB versions, nor the Compute Module 4.
* *power supply*
* *64GB micro-SD card*. We'll be packing a lot of content on here. USB storage is _way_ faster, but ???
* *keyboard*, *video monitor* and *mouse*. This hardware combination is so common it used to be abbreviated to KVM, until Kernel-based Virtual Machines came along and stole the acronym. 
* *HDMI cable*. This cable needs a micro-HDMI plug on the Pi end, and probably a full size HDMI plug on the other. 

No fan, no heatsink, no USB storage, no HAT.

Much of this hardware is only required to get started. 
When everything is set up, you can connect from another computer over the network to the Raspberry Pi and do everything you need on the CLI (Command Line Interface).



