= libvirt virtual machine 
Nick Hardiman 
:source-highlighter: pygments
:toc: 
:revdate: 21-11-2020


Create a virtual machine to check the libvirt system works. 
This is a short-lived VM - it's created, checked, then deleted.
The VM and its storage volume are called _does-it-work_.

The _rpi4_ machine is the physical machine that hosts the _does-it-work_ guest. 

.physical machine and virtual machine 
....
.------------------------.
|                        |
|  rpi4                  |
|                        |   
|   +----------------+   |    
|   |                |   |  
|   |  does-it-work  |   |
|   |                |   |   
|   +----------------+   |  
.------------------------.  
....



Grab another copy of the Fedora Minimal image and use it to create a VM. 
This image is not an install ISO - the OS is already installed. 

No VMs exist yet. 

[source,console]
----
[root@rpi4 images]# virsh list --all
 Id   Name   State
--------------------

[root@rpi4 images]# 
----


== create the storage volume 

We've already used one of Fedora's https://alt.fedoraproject.org/alt/[alternate architecture] downloads to boot the Raspberry Pi 4. 
Use another copy of the https://download.fedoraproject.org/pub/fedora-secondary/releases/33/Spins/aarch64/images/[Fedora Minimal image] for ARM® aarch64 Architecture to boot a new virtual machine. 

Use a web browser to copy the download URL.
 
* Look at the https://download.fedoraproject.org/pub/fedora-secondary/releases/33/Spins/aarch64/images/[list of images].
* Find the latest file. It's named something like _Fedora-Minimal-33-1.3.aarch64.raw.xz_.
* Copy the link. 

Use a CLI to get the image. 

* Use the root account. 
* Look at the HTTP headers. You don't get the file, you get a redirect to another service. The URL https://download.fedoraproject.org/pub/fedora-secondary/releases/33/Spins/aarch64/images/Fedora-Minimal-33-1.3.aarch64.raw.xz will return a 302 code and another location for the image file.

[source,console]
----
[root@rpi4 ~]# cd /var/lib/libvirt/images/
[root@rpi4 images]# 
[root@rpi4 images]# FILE=https://download.fedoraproject.org/pub/fedora-secondary/releases/33/Spins/aarch64/images/Fedora-Minimal-33-1.3.aarch64.raw.xz
[root@rpi4 images]#
[root@rpi4 images]# curl -i $FILE 
HTTP/2 302 
date: Sat, 21 Nov 2020 11:06:09 GMT
server: Apache
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: same-origin
location: http://mirrors.dotsrc.org/fedora-buffet/fedora-secondary/releases/33/Spins/aarch64/images/Fedora-Minimal-33-1.3.aarch64.raw.xz
content-type: text/plain
content-length: 0
apptime: D=4037
x-fedora-proxyserver: proxy36.fedoraproject.org
x-fedora-requestid: X7j0obpARiOhchQcD-yVLQAKAgk

[root@rpi4 images]# 
----

* Download, telling curl to follow redirects like the one in these headers (that's what the --location option does here) and to save the file with the same name (--remote-name).

[source,console]
----
[root@rpi4 images]# curl --location --remote-name $FILE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  876M  100  876M    0     0  7281k      0  0:02:03  0:02:03 --:--:-- 8863k
[root@rpi4 images]# 
----


* Extract the image from the downloaded file. Uncompressing the file takes a while because write speed on an SD card is not great. 

[source,console]
----
[root@rpi4 images]# unxz  Fedora-Minimal-33-1.3.aarch64.raw.xz 
[root@rpi4 images]# 
----


*  Check SELinux. The SELinux file type is _virt_image_t_. That's fine. 

[source,console]
----
[root@rpi4 images]# getenforce
Enforcing
[root@rpi4 images]# 
[root@rpi4 images]# ls -laZ
total 2381720
drwx--x--x.  2 root root system_u:object_r:virt_image_t:s0           4096 Nov 21 11:20 .
drwxr-xr-x. 10 root root system_u:object_r:virt_var_lib_t:s0         4096 Nov 20 17:19 ..
-rw-r--r--.  1 root root unconfined_u:object_r:virt_image_t:s0 5368709120 Nov 21 11:19 Fedora-Minimal-33-1.3.aarch64.raw
[root@rpi4 images]# 
----

Create a copy of this raw image. 
The copy gets used by the machine, leaving the downloaded version untouched. 

[source,console]
----
[root@rpi4 images]# cp Fedora-Minimal-33-1.3.aarch64.raw does-it-work.raw
[root@rpi4 images]# 
----



== create the virtual machine 

Create a VM using the ready-made Fedora disk image. 

A new VM can be created using a command like ``virsh define my-machine.xml``, 
similar to the way a storage pool can be created using ``virsh pool-define storage-pool.xml``.
But the XML configuration that defines a virtual machine is complicated. 
It's easier to use the ``virt-install`` command to do the hard work. 

This ``virt-install`` command is pretty long. 
The first option sets the name. 
The next three options add resources - 1 CPU, 1024MiB memory and the 5GiB disk.
The boot option sets the firmware -   UEFI rather than the older BIOS.
The os-variant option sets up some default values.
There are no graphics, so this machine can only be connected to using a serial console.  
And finally the virt-install command kicks off the build of the VM but doesn't hang around and connect to the console. 
That's done as a seperate step. 

[source,console]
----
virt-install \
  --name="does-it-work" \
  --vcpus=1 \
  --ram=1024 \
  --disk path=/var/lib/libvirt/images/does-it-work.raw \
  --boot uefi \
  --os-variant fedora33 \
  --graphics none \
  --noautoconsole
----

libvirt adds XML configuration 

[source,console]
----
[root@rpi4 images]# virt-install \
>   --name="does-it-work" \
>   --vcpus=1 \
>   --ram=1024 \
>   --disk path=/var/lib/libvirt/images/does-it-work.raw \
>   --boot uefi \
>   --os-variant fedora33 \
>   --graphics none \
>   --noautoconsole

Starting install...
Domain creation completed.
[root@rpi4 images]# 
----

Now there is a VM.

[source,console]
----
[root@rpi4 images]# virsh list --all
 Id   Name           State
------------------------------
 1    does-it-work   running

[root@rpi4 images]# 
----


A storage pool has been automatically created. 
Libvirt creates a new XML configuration file /etc/libvirt/storage/images.xml. 

[source,console]
....
[root@rpi4 images]# virsh pool-list
 Name     State    Autostart
------------------------------
 images   active   yes

[root@rpi4 images]# 
....




== use the console 

Connect to the console with the ``virsh console`` command.
It takes a minute for boot-up to finish, so you may see many boot-up messages appearing on the console. 
Finally anaconda starts to handle the install process, and stops at the first interactive prompt. 


[source,console]
----
[root@rpi4 images]# virsh console does-it-work
Connected to domain does-it-work
Escape character is ^] (Ctrl + ])
[  OK  ] Finished Rebuild Hardware Database.
         Starting Rule-based Manage…for Device Events and Files...
[  OK  ] Started Rule-based Manager for Device Events and Files.
[  OK  ] Finished Monitoring of LVM… dmeventd or progress polling.
...
================================================================================
1) [x] Language settings                 2) [x] Time settings
       (English (United States))                (US/Eastern timezone)
3) [x] Network configuration             4) [x] Root password
       (Wired (enp1s0) connected)               (Disabled. Set password to
                                                enable root account.)
5) [ ] User creation
       (No user will be created)

Please make a selection from the above ['c' to continue, 'q' to quit, 'r' to
refresh]: 
----

That's enough to prove the virtual machine runs. 

Disconnect from the console. 
The disconnection command is ``ctrl`` + ``]``

[source,console]
----
^]
[root@rpi4 images]# 
----


== stop the VM

Usually we stop a VM with the command ``virsh shutdown guest1``. 
This is a graceful shutdown, like running ``systemctl poweroff``.

But here we want to pull the plug, using ``virsh destroy guest1``.
Despite the dramatic _destroy_ name, this does not delete anything. 

[source,console]
----
[root@rpi4 images]# virsh destroy does-it-work
Domain does-it-work destroyed

[root@rpi4 images]# 
----


== delete the VM

Delete the new VM with the command  ``virsh undefine``.

[source,console]
----
[root@rpi4 images]# virsh undefine --nvram does-it-work 
Domain does-it-work has been undefined

[root@rpi4 images]# 
----

Check it's gone. 

[source,console]
....
[root@rpi4 images]# virsh list --all
 Id   Name   State
--------------------

[root@rpi4 images]# 
....


