= operating system  
Nick Hardiman 
:source-highlighter: pygments
:revdate: 24-10-2020

!!! copying this
https://fedoramagazine.org/install-fedora-on-a-raspberry-pi/

The computer needs an OS. 
Fire up the Raspberry Pi 4 with Fedora.

== what is an OS 

It's easier to define what an OS is by going back to the era before Linux, and get a definition from the people who created UNIX. 
If you watch this https://techchannel.att.com/showpage/ATT-Archives[AT&T Archives]  video
https://techchannel.att.com/playvideo/2014/01/27/ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use["The UNIX System: Making Computers Easier to Use"], you'll see https://en.wikipedia.org/wiki/Victor_A._Vyssotsky[Victor Vyssotsky] define an operating system and https://en.wikipedia.org/wiki/Dennis_Ritchie[Dennis Ritchie] describe the parts of the UNIX OS.
You'll also see an amazing array of 1982 sweaters. 


=== parts of an OS 

In the video, https://en.wikipedia.org/wiki/Dennis_Ritchie[Dennis Ritchie] says 
"the UNIX operating system is basically made up of three parts. 
The kernel, or operating system proper, is the part that manages the control of the machine, and supervises scheduling of the various user programs. 
The shell, which is the name we give to the command interpreter, looks after the communication between the user and the system itself. 
The third part, which is actually the largest, is the various utility programs which perform specific tasks like editing a file or sorting a bunch of numbers or making a plot. 
In other words, all the other programs that are not provided directly as part of the operating system kernel".



=== operating system software versus application software

Operating system is a collective term for software that makes a computer work, and that means different things to different people. 
Is the kernel the only true OS software? 
Does the list of utility programs include the graphical desktop?  
Where does operating system software stop and application software start? 

Vyssotsky says "The programs which tell a computer how to switch a telephone call, or compute a payroll, or play an electronic game are called application software. There's another type of software, the programs which control the resources of the computer itself - the memory of the computer, the processing elements, and the terminals connected to the computer. This latter type of software is called an operating system. Another way of saying what an operating system is, is that it's a collection of programs which make the intricate hardware of the computer seem more simple and comprehensible from the point of view of an applications programmer, so that the applications programmers can create software more easily". 




== download Fedora 33 Minimal

!!! 24 Oct 20 Fedora 33 not here yet
this is all temporary.

* Find Fedora's https://alt.fedoraproject.org/alt/[alternate architecture images].  
* https://kojipkgs.fedoraproject.org/compose/33/latest-Fedora-33/compose/Spins/aarch64/images/[AArch64 images]
* Download the latest minimal image, named something like _Fedora-Minimal-33-1.2.aarch64.raw.xz_. 


The _Fedora Minimal_ image, one of https://alt.fedoraproject.org/[Fedora’s alt downloads], contains three partitions.

* the https://en.wikipedia.org/wiki/EFI_system_partition[EFI system partition]
* boot partition
* root partition

The image contains a ready-made file system, with over 400 packages already installed. 
This minimal image does not include popular packages like a development environment, Internet service or desktop.
These types of software aren’t required for this work. 
While this is the first Raspberry Pi to comfortably fit a graphical desktop, there's no need to waste a GB running one.

The downloaded file is compressed and about 700MB in size. 
When the file is uncompressed, it’s 5GB. 
It’s an ext4 file system that’s using about half of that 5GB. 
All that empty space is the reason the compressed download is so much smaller than the uncompressed raw image.

== copy to the micro-SD card

* Copy the image to a micro-SD card.

This can be a more complex than it sounds, and a painful experience. 
Finding a https://www.jeffgeerling.com/blog/2019/raspberry-pi-microsd-card-performance-comparison-2019[good micro-SD card] takes work. 
Then there’s the challenge of physically attaching the card to your computer.
Perhaps your laptop has a full SD card slot and you need a card adapter, or perhaps you need a USB adapter. 
Then, when it comes to copying, the OS may either help or get in your way. 
You may have luck with https://fedoramagazine.org/make-fedora-usb-stick/[Fedora Media Writer], or with these Linux commands.

[source,shell]
----
unxz ./Fedora-Minimal-32-1.6.aarch64.raw.xz
dd if=./Fedora-Minimal-32-1.6.aarch64.raw of=/dev/mmcblk0 bs=8M status=progress oflag=direct
----

set up Fedora

* Connect the Pi, power cable, network cable and micro-SD card.
* Hit the power.
* Wait for the https://fedoraproject.org/wiki/Anaconda[anaconda installer] to start.
* Answer anaconda’s setup questions.

Initial configuration of the OS takes a few minutes – a couple minutes waiting for boot-up, and a couple to fill out the spokes of anaconda’s text-based installer. 
Write down your root and user passwords somewhere safe. 

I set mine up with a user named _nick_ who is an administrator (a member of the _wheel_ group). 

After setup, the login prompt appears.  
Log in with the _root_ account. 
The prompt shows the host name is set to _localhost_. 

[source,shell]
----
[root@localhost ~]# 
----

Congratulations! Your Fedora Pi is up and operational.

== check your work 

Power down the Pi, then power it back up again. 

Power down. 

* Power down with `systemctl poweroff`.
* Wait a few seconds. The screen goes dark and the activity LED on the board stops flashing.
* Switch off the power. 

Power up. 

* Switch on the power. 
* Wait a few seconds. Bootloader messages briefly appear, followed by the login prompt. 
* Log in with the root account. 


