= use the Bash shell 
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 16-10-2020

Bash knowledge is not shared out equally. 
Some knowledge is universal - you can't use Bash for five minutes without running _ls_. 
And some knowledge is arcane, like job control.

This is not a bash tutorial. If you really want to find out what Bash is capable of, read the https://www.gnu.org/software/bash/manual/bash.html[manual]. 

If you after simple gratification, play around with these commands. 



== the GNU Bash process

After logging in, you find yourself using GNU Bash, version 5. 
The OS is running a Bash process for you. 
The `ps` command lists running processes. 
While it's busy listing running processes, it lists itself because ps is a running process.

[source,shell]
----
[nick@rpi4 ~]$ ps
    PID TTY          TIME CMD
   3361 pts/0    00:00:00 bash
   3771 pts/0    00:00:00 ps
[nick@rpi4 ~]$ 
----

* PID (Process ID) - Many things in Linux get a number, including running processes. 
* TTY (TeleTYpe) - the terminal you are using to read and write. 
* TIME - how much CPU time you have used up, in the format hours:minutes:seconds. These commands have so far used less than a second.
* CMD The command that started this process


== view resource files 

The home directory contains many configuration files. 
They are known as dotfiles, or hidden files - they start with "." and Bash doesn't display them.

[source,shell]
---- 
[nick@rpi4 ~]$ ls -d .*
.   .bash_history  .bash_profile  .cache   .local    .ssh
..  .bash_logout   .bashrc        .config  .mozilla
[nick@rpi4 ~]$ 
----

* .bash_history  - a list of all the commands you have run so far. To see the maximum number of commands this stores, run _echo $HISTSIZE_.
* .bash_logout  - When Bash exits, any commands in here are run. Usually, no-one bothers adding any. 
* .bash_profile  - This is the traditional place for a user to add their own customized settings. There's a similar file (/etc/profile) that defines settings everyone gets. 
* .bashrc  - functions and aliases. You also get everything in /etc/bashrc.
* .ssh - This one's actually a directory used by SSH, not Bash.

If you want to know more about dotfiles, read this great https://fedoramagazine.org/customizing-bash/[Customizing Bash] article.



=== examine the prompt 

Ever wondered why the prompt looks like this? 

[source,shell]
---- 
[nick@rpi4 ~]$ 
----

A special set of symbols define how the prompt looks. 

[source,shell]
---- 
[nick@rpi4 ~]$ echo $PS1
[\u@\h \W]\$
[nick@rpi4 ~]$ 
----

To play around with the prompt layout, look at the man page (_man bash_) and search for _PROMPTING_. 
It has a big list of these backslash-escaped special characters.


=== try completion 

Typing long commands is annoying. 
That's why the GNU project added  https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html[programmable completion].
The easiest completion is typing the first few characters of a command (three usually does it) and hitting the tab key (⇥). 

[source,shell]
---- 
[nick@rpi4 ~]$ host⇥
host         hostid       hostname     hostnamectl  
[nick@rpi4 ~]$ host
----

Try the same thing with less letters and more tabbing. 
Entering _hos_ and hitting tab only matches _host_, so that appears on the same line.  
Hitting tab twice more displays the list of commands that start with _host_.

