= why RHEL
Nick Hardiman
:source-highlighter: highlight.js

Red Hat 
https://www.redhat.com/en/blog/red-hat-leading-enterprise-linux-server-market[leads the enterprise server market].



== why install RHEL

A serious home lab deserves a serious software stack. 

You want to ...

* check out what's changed between RHEL 7 and RHEL 8. 
* uninstall and reinstall services without annoying your colleagues. 
* put in some R&D time with virtual machines and containers.
* practice your sysadmin skills with the world's leading enterprise platform. 
* litter your workspace with developer tools.


== why not use Fedora instead

https://www.redhat.com/en/topics/linux/fedora-vs-red-hat-enterprise-linux

The focus of RHEL 8 is to be stable in production. 
Enterprise-grade scalability.
A lot of updates are produced. Bugs are fixed, vulnerabilities are removed, and features are enhanced. 
Major versions stay put. Minor version upgrades are checked to make sure they don't break anything. 
A lot of security work is done, like compiling more securely and certifying against security standards. 

