= Introduction
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 01-03-2021

== Red Hat's management technology

Red Hat supports many tools for automation and management.

* https://www.redhat.com/en/technologies/management/ansible[Red Hat Ansible Automation Platform]
* https://www.redhat.com/en/technologies/management/satellite[Red Hat Satellite]
* https://www.redhat.com/en/technologies/management/insights[Red Hat Insights]

https://www.ansible.com/products/engine[Ansible Engine] is one of Red Hat's products in the Automation Platform. Ansible Engine is an automation system, good for provisioning new systems and deploying applications. 
Thousands of modules are included to manage Linux, Windows, on-premise network kit, off-premise cloud services, physical machines and virtual.


== prerequisites 

This article assumes you have already carried out these steps.  

. sign up for a developer account.
. prepare your workstation
. install RHEL 8
. complete system registration and subscription  

There are  many commands shown here, along with their output. 
After you carry out these steps, you will see the same results when you run the commands.

Start the VM.

Log in.

[source,shell]
....
[nick@workstation ~]$ ssh 192.168.1.218
nick@192.168.122.218's password: 
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Wed May 27 13:26:47 2020
[nick@host1 ~]$ 
....
